### ISSUE TITLE
REST API to list all the rooms

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#101]
Discord feedback: https://discord.com/channels/913109211746009108/913157273046646795/956834391559139358

**Comment by stevenfabre** [comment]
Nico Bachner also asked for this on Discord: https://ptb.discord.com/channels/913109211746009108/913109211746009112/960848136027398194

**Comment by GuillaumeSalles** [comment]
Initial version released: https://liveblocks.io/docs/api-reference/rest-api-endpoints#GetRooms
