### ISSUE TITLE
[BUG] Incorrect icon sizes in mobile menu for `/docs`

### ISSUE THREAD

**Issue by RickyC0626** [liveblocks/liveblocks#1016]
**Illustrations**

![image](https://github.com/liveblocks/liveblocks/assets/24194862/d3888f26-bafc-4c67-8759-46eba02d38c6)

**Comment by nvie** [comment]
cc @pierrelevaillant

**Comment by pierrelevaillant** [comment]
Fixed!

Thanks for spotting this @RickyC0626 🙏
