### ISSUE TITLE
Missing StopRetrying Mechanism for Auth Callback method

### ISSUE THREAD

**Issue by horationunez** [liveblocks/liveblocks#1017]
**Describe the bug**

Custom Auth Callback mechanism doesn’t honor 401. Neither (it seems) has a way to convey an “stopRetrying” message to the Liveblocks client.

**To Reproduce**

1. Provide a callback method2. 
2. Wait until token in your own system expires.
3. Get a 401 from your own endpoint

**Expected behavior**

401 is honored 

Environment (please complete the following information):**

- Liveblocks packages and packages version [e.g.]
  @liveblocks/client@1.1.x]
- Browser's version [e.g. chrome v99.0.4, safari]
- [...]

**Additional context**

This is the docs page that describes the auth callback approach: https://liveblocks.io/docs/api-reference/liveblocks-client#createClientCallback

**Comment by nvie** [comment]
Hmm, that's a good point. We'll have to get this fixed. Thanks for reporting, @horationunez!

**Comment by horationunez** [comment]
@nvie is this something that we can contribute directly? we have been looking at your core library and know where to do the fix.

**Comment by horationunez** [comment]
@nvie having the ability to stop retrying will work for us. Do you foresee a way in which I could signal the library try again in a few seconds as well? For context, our implementation is for Angular.

**Comment by horationunez** [comment]
I tried creating a PR in your library: https://github.com/liveblocks/liveblocks/pull/1021

**Comment by nvie** [comment]
We've just published a fix for this as part of [1.1.7](https://github.com/liveblocks/liveblocks/releases/tag/v1.1.7). Thanks for bringing this to our attention, @horationunez 🙏 !
