### ISSUE TITLE
Rest API response improvements

### ISSUE THREAD

**Issue by andreaselia** [liveblocks/liveblocks#108]
It would be great if the API endpoints returned appropriate error messages rather than 404 status codes.

Maybe a JSON object with a message as to why it failed, or simply changing the returned status code from 404 to something a little more relevant to the issue with the request.

**Comment by vinodsantharam** [comment]
Hi @andreaselia! Thanks for your feedback. It's definitely on our roadmap. Your wish will come true soon!
