### ISSUE TITLE
Support Redux/Zustand: Handle multiple `RoomProvider`

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#1081]
Ensure we can use multiple `RoomProvider` connected to the same room. This should also enable us to use `RoomProvider` while using `@liveblocks/zustand` / `@liveblocks/redux`

Two parts:
- Support multiple RoomProviders for the same room ID in different component trees in the same app
- Support nesting RoomProviders (or prevent that explicitly)

**Comment by adigau** [comment]
Guillaume to talk to Vincent to take on that task

**Comment by nvie** [comment]
This was actually still on my todo list, just haven't had the time to start on the implementation yet. But happy to do put it a little bit higher on the priority list if we want to tackle this now 👍

**Comment by nvie** [comment]
Fixed by #1226 , will land in 1.5.
