### ISSUE TITLE
Few extra milliseconds taken while navigating through sidebar

### ISSUE THREAD

**Issue by Neon-20** [liveblocks/liveblocks#1118]
**Describe the bug**

Hi Team, So I was going through Liveblocks.io and I figured out that when I am navigating from one section to another its taking unusual amount of time.
I just wanted to know whether it's intended or it's a small lag.
If you guys can clarify then i could work on this issue.
☺️
**To Reproduce**

1. Open App
2. Make account
3. Navigate through sidebar

**Expected behavior**

The intended page should load up in a flash.

**Illustrations**
https://github.com/liveblocks/liveblocks/assets/55043383/4667a45e-9fe4-45a9-807d-992888195ed2

**Environment (please complete the following information):**

- Liveblocks packages and packages version [e.g. @liveblocks/react@0.15.1
  @liveblocks/client@0.15.1]
- Browser's version [e.g. chrome v99.0.4]

**Comment by Neon-20** [comment]
Yeah, although the issue seems to go away now, since I have been using @liveblocks actively.
Thanks @adigau

**Comment by nimeshnayaju** [comment]
Hi @Neon-20, I wanted to provide you with an update on the performance issue you reported. Last week, we addressed several performance concerns on the dashboard. Please note that the recent improvements have been applied to specific routes, so you might still experience some delays when navigating other routes. We have taken note of these remaining issues and will focus on resolving them as soon as we can.

Thank you for bringing this to our attention. Have a great week!
