### ISSUE TITLE
[Feature Request] View Room Metadata and Accesses in Dashboard

### ISSUE THREAD

**Issue by gerardSlate** [liveblocks/liveblocks#1146]
**Is your feature request related to a problem? Please describe.**

During development, I've found it difficult to inspect the underlying data that constitutes a Room. Namely, I need a way to validate that I am writing metadata, and updating permissions correctly without having to fetch and log the Room response.

**Describe the solution you'd like**

In the dashboard, we already have two tabs one for storage and one for yjs. I request adding another tab that displays the room metadata, and permissions as well.

**Additional context**

None

**Comment by nvie** [comment]
This is something we have always wanted to add to the dashboard, just haven't built yet. I'll take this to the team, as I agree this would be very useful 👍

**Comment by adigau** [comment]
Hello @gerardSlate, if you visit your Liveblocks dashboard you should find something you've been wanting for a while now :) 

Is there anything else missing according to you?

**Comment by gerardSlate** [comment]
> Hello @gerardSlate, if you visit your Liveblocks dashboard you should find something you've been wanting for a while now :)
> 
> Is there anything else missing according to you?

WOO!! Love it! Thank you!
