### ISSUE TITLE
[Feature Request] Typed API Client

### ISSUE THREAD

**Issue by gerardSlate** [liveblocks/liveblocks#1147]
**Is your feature request related to a problem? Please describe.**

I'm using the REST API to execute fetches for room data (metadata, permissions, etc.). Currently, I'm using `axios` to dispatch requests which is fine but it would be nice to have a typed client similar to this:

`const liveblocks = new Liveblocks({ secret: SECRET_KEY! });`

**Describe the solution you'd like**

It would be great if we could either expose additional methods on the existing Liveblocks class or create a dedicated typed REST client.

```
interface LiveBlocks {
  ... existing liveblocks methos
  getRoom(id: string): Promise<Room>
  getRooms(): Promise<Array<Room>>
  etc..
}
```

**Comment by nvie** [comment]
This is absolutely something we want to offer in our `@liveblocks/node` API, it just hasn't been implemented yet. I'll take this to the team 👍

**Comment by khareyash05** [comment]
Hi @nvie . I would love to use the `@liveblocks/node` api. Also I would love to contribute to the same. Is there somewhere I can access the same?

**Comment by Nick-Lucas** [comment]
What would it take to at least expose OpenAPI definitions on the RestAPI? Generators are excellent these days so that way we could generate clients in whatever language we like and get full type safety.

It's one of the few surprising aspects of liveblocks so far, that there's a REST API but no client or even OpenAPI definitions available

**Comment by adigau** [comment]
Hello everyone, we just added all our REST APIs as fully typed methods to Liveblocks client. See [docs](https://liveblocks.io/docs/api-reference/liveblocks-node#Liveblocks-client).
