### ISSUE TITLE
Collaborative Cursors + Selected text Flicker for Tiptap + YJS 

### ISSUE THREAD

**Issue by YassineRjl** [liveblocks/liveblocks#1161]
**Describe the bug**

I noticed the carets for remote users flicker when the editor (TipTap) is focused. Please check the recording.

**To Reproduce**

1. Run https://github.com/liveblocks/liveblocks/tree/main/examples/nextjs-yjs-tiptap-advanced

Note: I tried with npm 10.1.0

**Expected behavior**

The remote cursors + selections don't flicker.

**Illustrations**

https://github.com/liveblocks/liveblocks/assets/33147103/c75d216f-7da0-4d4f-9779-b7fec46e92a2

**Environment (please complete the following information):**

- Chrome 116.0.5845.187 (Official Build) (arm64)

**Comment by YassineRjl** [comment]
Update: I tried with the TipTap provider, and it still flickered.

But, it's now working as expected on both NextJs & ReactJs after building and serving the static files. For some reason running "yarn start" for react or "yarn dev" for nextjs gets the cursor to flicker. So yeah just build and start

**Comment by CTNicholas** [comment]
Thanks for letting us know! I've been looking into this one already—as you said, I believe it only happens in development mode, and I think it could be a problem with the CollaborationCursor plugin. I'll make a bug report.

**Comment by CTNicholas** [comment]
I've already been reported! https://github.com/ueberdosis/tiptap/issues/4482
