### ISSUE TITLE
[nextjs-comments] TypeError: e.reactions is undefined

### ISSUE THREAD

**Issue by esau-morais** [liveblocks/liveblocks#1201]
**Describe the bug**

TypeError: e.reactions is undefined

Might be related to this [file](https://github.com/liveblocks/liveblocks/blob/main/packages/liveblocks-react-comments/src/components/Comment.tsx#L363)

**To Reproduce**

1. Go to example
2. Comment an emoji in a new comment
3. See error

**Expected behavior**

Get to comment emojis properly

**Illustrations**

![image](https://github.com/liveblocks/liveblocks/assets/55207584/005c0843-6bbf-47d2-bbf3-b706df4072ee)

**Comment by marcbouchenoire** [comment]
This was fixed by https://github.com/liveblocks/liveblocks/pull/1203 and released with `v1.4.5`.
