### ISSUE TITLE
session.authorize returns 503 

### ISSUE THREAD

**Issue by didemkkaslan** [liveblocks/liveblocks#1299]
**Describe the bug**

I have implemented next-auth for auth purposes. And below is my auth endpoint for liveblocks. It used to work seamlessly but for the past 1 2 days sometimes it stops working and giving me error I posted below 

```
// liveblocks-auth/route.ts
import { getUser } from '@/lib/getUser';
import { Liveblocks } from '@liveblocks/node';
import { v4 } from 'uuid';

const liveblocks = new Liveblocks({
  secret: process.env.LIVEBLOCKS_SECRET_API_KEY,
});

export async function POST(request: Request) {
  const { room } = await request.json();

  const dbUser = await getUser();

  const avatarId = v4();

  const user = dbUser || {
    id: avatarId,
    name: 'Anonymous',
    image: `https://avatar.vercel.sh/${avatarId}.png`,
  };

  // Start an auth session inside your endpoint
  const session = liveblocks.prepareSession(user?.id, {
    userInfo: {
      name: user.name,
      image: user.image,
    },
  });

  if (room) {
    session.allow(room, session.FULL_ACCESS);
  }

  // Authorize the user and return the result
  const { status, body, error } = await session.authorize();

  console.log('status', error);
  return new Response(body, { status });
}
```

**To Reproduce**

1. pnpm run dev

**Expected behavior**

session.authorize() should work and I should see my livee cursorss

**Illustrations**

If applicable, add screenshots or video recordings to help explain your problem.
Upload your file with a drag and drop on the text area.

<img width="549" alt="Screenshot 2023-11-08 at 20 38 52" src="https://github.com/liveblocks/liveblocks/assets/106841409/ed379c0b-802a-484e-a864-3e3f915e78b2">

<img width="848" alt="Screenshot 2023-11-08 at 20 39 25" src="https://github.com/liveblocks/liveblocks/assets/106841409/dbac28e6-c779-4571-937a-2407c9b0a288">

**Environment (please complete the following information):**

"@liveblocks/client": "^1.7.0",
"@liveblocks/node": "^1.7.0",
"@liveblocks/react": "^1.7.0",
"@liveblocks/react-comments": "^1.7.0",

**Comment by nvie** [comment]
Hey! Getting a `ENOTFOUND` from the `getaddrinfo` syscall typically indicates an unreachable host or a network or connectivity issue on your local network. We haven’t seen any downtime in the last couple of days, so maybe it’s best to check and see if there is perhaps a local network or firewall issue that plays up intermittently on your end? Have you seen connectivity issues with other services maybe as well? When these happen, how quickly do they resolve for you?

**Comment by didemkkaslan** [comment]
Thanks @nvie . No connectivity issues with other services. It seems like the hiccup is specifically with liveblocks, and when it happens ( for the last 1 2 day actually )  it hangs around for about 5 minutes. I'll dig into my local network and firewall settings to see if there's any mischief going on there. Appreciate the guidance!

**Comment by nvie** [comment]
Best of luck with that! I'll keep an extra eye out in our logs and look out to see if other people also are running into this issue.
