### ISSUE TITLE
Collaborative text editor with Tiptap and Yjs not syncing

### ISSUE THREAD

**Issue by henriquedevelops** [liveblocks/liveblocks#1344]
I'm trying to make an already existing text editor multiplayer using Liveblocks, Tiptap and Yjs.

I followed [this example](https://liveblocks.io/examples/collaborative-text-editor/nextjs-yjs-tiptap) from the documentation, but it isn't working and there aren't any error messages anywhere. The real-time updates simply don't happen.

I downloaded Liveblocks Devtools extension for Google Chrome. There I can see the room, and inside the room, I can see the presence of the 2 accounts that I'm using for testing:

![Screenshot 2023-12-10 161039](https://github.com/liveblocks/liveblocks/assets/47286998/63da0f84-2cfd-442c-812c-ecc6d4a00d85)

So I guess the core functionality must be working, but there must be something missing.

I would appreciate any ideas.

Thanks.

**Comment by stevenfabre** [comment]
Hi @henriquedevelops, thanks for reaching out. This should work and is most likely a problem in the setup. Are you able to share a CodeSandbox project so we can investigate what could be causing this issue?

**Comment by henriquedevelops** [comment]
Hi @stevenfabre thanks for replying

I managed to solve this issue by executing the useSelf hook in the parent component instead of the TiptapEditor component and then rendering the TiptapEditor component only when the value of the userInfo is truthy:

```
const TiptapDocProvider: React.FC<TiptapRoomProviderProps> = (props) => {
  const [yDocState, setYDocState] = useState<Y.Doc>();
  const [yProviderState, setProviderState] = useState<any>();
  const room = useFdocRoom();
  const userInfo = useFdocSelf((me) => me.info);

  useEffect(() => {
    const yDoc = new Y.Doc();
    const yProvider = new LiveblocksProvider(room, yDoc);

    setYDocState(yDoc);
    setProviderState(yProvider);

    return () => {
      yDoc?.destroy();
      yProvider?.destroy();
    };
  }, [room]);

  if (!yDocState || !yProviderState || !userInfo) {
    return null;
  }

  return (
    <Tiptap {...props} yDocState={yDocState} yProviderState={yProviderState} user={userInfo} />
  );
};
```

But now I'm getting another issue: #1347

**Comment by CTNicholas** [comment]
Hey, I'm glad you managed to solve this issue!
