### ISSUE TITLE
Unable to select any text when using liveblocks with cursors

### ISSUE THREAD

**Issue by azivkovi** [liveblocks/liveblocks#1353]
When using live cursors to update presence with cursor coordiantes, because of constant state updates you are unable to select text on screen because selection gets cleared when the state updates. With cursors sthate updates very frequently.

To reproduce, load liveblocks demo with cursors: https://liveblocks.io/examples/live-cursors-scroll/nextjs-live-cursors-scroll
If you edit the example to stop calling the `useLiveCursors` function, the text is selectable as expected.

Is this a bug and is there a way to go around this behaviour when using liveblocks?

**Comment by CTNicholas** [comment]
Hey @azivkovi, we mistakenly added `e.preventDefault()` to this example! You can see this fix here:
https://github.com/liveblocks/liveblocks/pull/1361
