### ISSUE TITLE
Problem to fetch data from Liveblocks API when not setting a schema

### ISSUE THREAD

**Issue by wesleyricarte** [liveblocks/liveblocks#1397]
# Describe the bug

When a schema is not set, Liveblocks API can't recognize type of data correctly. It seems like the data is recognized by the first charactere, like in the following requests.

GET https://api.liveblocks.io/v2/rooms?metadata.ehr=123abc
RESPONSE 200OK // good answer

GET https://api.liveblocks.io/v2/rooms?metadata.ehr=abc123
RESPONSE 422 Unprocessable Entity // here is the problem
```
{
    "error": "UNPROCESSABLE_ENTITY",
    "message": "Value at key \"metadata\": Either:\n- Must be undefined\n- Value at key \"ehr\": Invalid value. Must be alphanumeric, '_', '-', '@', '.' or '+'",
    "suggestion": "Please ensure the data follows the correct format",
    "docs": "https://liveblocks.io/docs/api-reference/rest-api-endpoints"
}
```
 
## To Reproduce
Try strings starting with numbers and starting with letters. It's needed Bearer API Token valid.

## Expected behavior

- Correct identification of the type of values;
- Or at least a good explanation of that in the docs please.

## Illustrations
![image](https://github.com/liveblocks/liveblocks/assets/110259771/4e34b5b8-537f-42c1-8f0a-c81689a7fa8b)
![image](https://github.com/liveblocks/liveblocks/assets/110259771/75b1e78c-3896-4984-b65a-a7f2c59768f5)

**Comment by nvie** [comment]
This was indeed an issue with our server side validation. It is now fixed. Please let us know if you still experience any issues! Thanks for reporting! (cc @FlowFlorent)

**Comment by wesleyricarte** [comment]
Thanks @nvie, tested here and it's solved.
