### ISSUE TITLE
useDeleteThread

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#1402]
Implement a hook to delete a thread from the client.
Require an additional admin permission for comments to be able to delete any threads.

### Definition

```typescript
function useDeleteThread(): ({ threadId: string }) => void;
```

### Usage

```typescript
const deleteThread = useDeleteThread();
deleteThread({ threadId: "th_xxx" });
```

**Comment by rahulbaghel007** [comment]
I read the documentation and research a lot and found some soution. can I contribute to this
