### ISSUE TITLE
YJS Integration Does not Appear to Fire Awareness `update` Event

### ISSUE THREAD

**Issue by jpulec** [liveblocks/liveblocks#1415]
**Describe the bug**
While trying to get Lexical collaboration working with liveblocks, I noticed that cursor/selection syncing wasn't working. I dug into the Lexical codebase to discover that the `CollaborationPlugin` syncs cursor state by listening to the `update` event on `provider.awareness`. After doing some logging, I discovered that the Liveblocks Provider does sync awareness state and the `change` event is emitted on `awareness`, but the `update` event never appears to be emitted.

Let me know if you need more info.

**To Reproduce**
Go to the example on the Liveblocks homepage and note that cursor state isn't synced for the Lexical/Yjs integration.

**Expected behavior**
Cursors should be synced up.

**Environment (please complete the following information):**

- Liveblocks packages and packages version: 
  -  `@liveblocks/yjs@1.9.6`
  -   `@liveblocks/client@1.9.6`
  -   `@liveblocks/react@1.9.6.`
  -   `lexical@0.12.5`
  -   `@lexical/yjs@0.12.5`

- Browser's version [e.g. chrome v99.0.4, safari]
  - Chrome 120.0.6099.216 (Official Build)

**Comment by jrowny** [comment]
We definitely do not send that event, so we'll need to add this. We'll work on it and add it soon!

**Comment by jpulec** [comment]
@adigau I believe this was fixed with #1427. Should be good to close.
