### ISSUE TITLE
Unexptected behavior if setting a default presence

### ISSUE THREAD

**Issue by jonassiewertsen** [liveblocks/liveblocks#148]
If setting a default presence, I would expect the username to be set and beeing available afterwards. 

My personal expectation would be, that the shown code examples would trigger the same behaviour. 
Setting the `name` via `updatePresence` works as expected. Using the defaultPresence (second example) will not return the name if calling `getPresence`.

![Bildschirmfoto 2022-04-14 um 11 20 24](https://user-images.githubusercontent.com/38906163/163355349-9955c960-c0a6-4b8e-b409-9e485d8e56d3.png)

_I am not sure if this is a Feature Request or a bug._

**Comment by ofoucherot** [comment]
Hi Jonas,
Thanks for reporting the issue.

We forgot to update our documentation, it's now up-to-date:
https://liveblocks.io/docs/api-reference/liveblocks-client#Client.enter

Here is the method to initialize the user presence when entering the room:
`client.enter("my-room", { defaultPresence: { cursor: null }});`
