### ISSUE TITLE
process is undefined error on Vite project

### ISSUE THREAD

**Issue by RenovationIGuess** [liveblocks/liveblocks#1557]
**Describe the bug**

My project is initialized with Vite and currently using version 1.10.0 for these 4 packages:
"@liveblocks/client": "^1.10.4",
    "@liveblocks/node": "^1.10.4",
    "@liveblocks/react": "^1.10.4",
    "@liveblocks/yjs": "^1.10.4",

But then I download the react-comments package and its latest version is 1.11.0. Then I met a conflict in versions so I upgraded all to 1.11.0 but since then I keep getting the **process is undefined** in the utils.ts file, which is the getBaseUrl function.

I have tried to go back to either 1.10.4 and 1.10.0 but none of them worked. Please help, I'm getting lost on how to solve this though I have look through a similar resolves issue which is solved in 1.10.4 but when I check the function getBaseUrl, it still using the process.env

**Comment by nvie** [comment]
Could it be that you’re still on an older version somehow? You can check with `npm ls` to see the exact installed versions in your project. If all versions of Liveblocks packages are on 1.10.4 or higher, then this should definitely not be happening. If so, please send us the ouput of your `npm ls`, and we can help you get unblocked.

**Comment by RenovationIGuess** [comment]
Thank you for reply me sir! Here is the npm ls result:
![image](https://github.com/liveblocks/liveblocks/assets/78362896/91750b7f-b66a-4ff6-80e7-31eba1e72fd1)

Here is the getBaseUrl
![image](https://github.com/liveblocks/liveblocks/assets/78362896/1d6d3170-f41a-44f9-86a2-c48962175bb3)

I just don't understand why is this happening @@

**Comment by nvie** [comment]
Ohh, it looks like we only addressed this issue in `@liveblocks/core`, and this is happening for you in `@liveblocks/node`. I’ll address this issue for you tomorrow morning and publish a fix! Thanks for reporting! 🙏

**Comment by RenovationIGuess** [comment]
Thank you sir! I hope you could fix it asap because I'm really in a rush, I need it to work so I can continue to code my graduation project. Again thank you and liveblocks team for created such amazing repo!

**Comment by nvie** [comment]
Fixed in [v1.11.1](https://github.com/liveblocks/liveblocks/releases/tag/v1.11.1)! Please let us know if this still isn't working for you.

**Comment by RenovationIGuess** [comment]
It worked! Thank you so much @nvie
