### ISSUE TITLE
Circular Reference in JSON

### ISSUE THREAD

**Issue by oravecz** [liveblocks/liveblocks#1559]
**Describe the bug**

I'm receiving a circular reference error after calling `room.getStorage()`, immediately after I create the room and initialize the data structure

```
TypeError: Converting circular structure to JSON --> 
  starting at object with constructor '_LiveList' | property '_items' -> 
    object with constructor 'Array' | index 0 -> 
      object with constructor '_LiveRegister' | property '_parent' -> 
        object with constructor 'Object' --- property 'node' closes the circle at JSON.stringify (<anonymous>) at ...
```

My call to `room.getStorage()`

```
const { room, leave } = client.enterRoom<Presence, Storage>(workbookId!, {
  initialPresence: { selectedItems: [] },
  initialStorage: {
    segments: new LiveList<EnsureJson<Segment>>(segments),
  },
});

const { root } = await room.getStorage();
```
I can successfully call `JSON.stringify(segments)`

```json
[
  {
    "id": "0F673P86P70WN",
    "route": "MFRAMR07458**C",
    "beginMeasure": 0.0143,
    "endMeasure": 0.1221,
    "segmentLength": 0.1078,
    "attributes": {
      "crossRouteTo": "SHANNON GREEN DR",
      "year": "2024",
      "pavementTypeCode": "01HBSHN89S5F7S3B44148QGKFM",
      "crossRouteToOffset": 0,
      "crossRouteFromOffset": 0,
      "project": "0F673P69TJCCG",
      "pavementActivityCode": "01HBSHN899AQCP0ZSJJFYN0F8Y",
      "program": "0F673P6A6MHDX",
      "crossRouteFrom": "FITZPATRICK BLVD",
      "estimateCost": 525926.02,
      "group": "0F673P68FHNSA"
    },
    "street": "VILLAGE GROVE LN"
  },
  {
    "id": "0F673P88Z753K",
    "route": "MFRAMR00269**C",
    "beginMeasure": 0,
    "endMeasure": 0.1336,
    "segmentLength": 0.1336,
    "attributes": {
      "crossRouteTo": "Alley: AL-32858",
      "year": "2023",
      "pavementTypeCode": "01HBSHN89S5F7S3B44148QGKFM",
      "crossRouteToOffset": 0,
      "crossRouteFromOffset": 0,
      "project": "0F673P67ZBG2S",
      "pavementActivityCode": "01HBSHN89AHH6SHNACWV90RMVZ",
      "program": "0F673P68B2ANY",
      "crossRouteFrom": "Terminus",
      "estimateCost": 493644.62,
      "group": "0F673P66JBAW6"
    },
    "street": "BERRELL AVE"
  },
  {
    "id": "0F673P8APQT2P",
    "route": "MFRAMR06417**C",
    "beginMeasure": 0,
    "endMeasure": 0.13,
    "segmentLength": 0.13,
    "attributes": {
      "crossRouteTo": "CAPE HENRY DR",
      "year": "2024",
      "pavementTypeCode": "01HBSHN89S5F7S3B44148QGKFM",
      "crossRouteToOffset": 0,
      "crossRouteFromOffset": 0,
      "project": "0F673P69YJMJV",
      "pavementActivityCode": "01HBSHN899AQCP0ZSJJFYN0F8Y",
      "program": "0F673P6A6MHDX",
      "crossRouteFrom": "Terminus",
      "estimateCost": 691654.62,
      "group": "0F673P68VW796"
    },
    "street": "LUCCIS CT"
  }
]
```

**To Reproduce**

[Live Example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wYQBthMA7GAGhThgE8xM4BRUgZwFcsApViUq1ABlgAN0zDWlJAF84AMygQQcAOQABYmIBGhCGgDWrAPRpiZGCoDcSJJgAekWHGDlMUOdjSMAgjBhRgLXY8fAhCQkw0GGA+RGpUAG19TFoALjhJANIAcwBddOxSWmtpG3tHeBc8d09GAGVMbJBzONRUYAATdMyXbOs2uEVgzG7-Xv62rUaXAFkcDix00nYQKagJ1DIOuewFkbhl1bcNjMbm8kEybJgACyWVtZPcMaC8VgB+dN8X4dDwyOifBOmUwmBgnwyYxyJRsaD4klOTXMrFSDSR5ASuTgAF44AlqMgBgAiTpE9JEgAMADEAGwAdgAzAAFAAcNKZdIpAHUAHJEgRtIlDPBkuBEmZUgBK3hmkopdIALABWFkAKlV+H58TFU2ys3mnEwoopADoKQBGBUMgWoIlbHZ7Y0m80AJhd5ptYtYZ3Mlxytyd5vlLM9ROeAVemFYosJAzFGAgrFYkogwwAKhBRUS6gAJbw8nkAeR5cAA4pKmEwSwARSVauNi2g4KBZl0Ul0K+txolgbBic4wNP0AgQDpG8kWnMAIVzPJZAE46kqqXS6gypwqFZaWQBFUsAaSpMy7xITSZT6Yghbkcm9MGNnttZ+TqbwVMUIGvt7BD+1trAigAFYAlm1L0syNLzmmXD4PgpYnoKvb9uY3hRKIwB0KEY6gea06zgu87eDu+BMhSABadRcFwVIAJo8tSLI0Qh-6KNkUDYCAoG0oyTI0t4NIzDm1YABrMfGijnq+mDvkoWZUgAkmmZFMt4aaSvJ+D7nAU6CAAatWYl2pIoC4COkiikqLpKvOLo0maLqPmKbGpmAXHgbxLJUjmPJ1N4RLatIoYgj+5K6fJgiCN4pZMGWkqFrpMWCHy1CBQS2okh0bk8SyLJkXSSoMvuCFClJWYStKsoUu2kHqpqoa6vquyGr+xL2gaWCBgyDI0kFPoXFcAbpKa5pdT16XhoEwzRuksanhJL6Xlm3j-GkcDeIIAC0DIuiyKqGU22AtuSbYugyhlIZgA5DgwWHjmKk4zt5C5Liua4bluCq7geR6Gc+F54BmX53i13Z-VJMmfjewNDY5PZASBE7cRBdJkVOpYunU519pdKFoSIGG0LdOF4U9hE5jmNKzt4+Bcrp84UpKMy6WR52sexnGI+5NIslOLr5kxsNg8MENZmmbggC47DRrDUbRCApmhOZ6QKvO3WbiaNIOX+TlDK5nM8TSNJcFO3hcjS-kDKlxLBfe5JTkwkoVhFa0JRbcBW60gqkvrzIst4TI7mmLpMsVwp3eKUoynKNJbnStXFQ1pAOs1MPpW1TUdUNzrWul3rojAfrXDcnWhhNkbTZ7c2JgtAOZuS+D+zFOZVpKNFwLW+3Nq27adrDF1XcORMTrhj1zouy6ruum7bnuh7HoL83-ZggNQyFcAUgv1dLxDQNrxv2twxAwFRFlEHzjRXAzFwulY8h5CodE+OYaO4cPfh86EcRpEUVRtH0VSjFWYQDYhxU+vF+KCREr9Re4MPyi3FpLaWB9ZYmRCImW2cBILmhpEqBUGstYNiJM5dget7pIw8rpLkdJ5zmwCkFfwoIMFEkEAAVVgvJOocB8BpjdqUXINgkB0AYHAJkWBvSkC8DiT2Us3CkA4pgCEPRoTUG9BEKImAOjyTwCAFEkIsjZExCUawgjhxwDqDAaA2BsiMFxLGPOA5dHCDEBIGAAAeFgeweB8FcWiAcAA+PxRjYTwngKYEg5ApEYBwCEMw5AAAUsYwDsB0MANA3gwDAH3CkVI2oVBgH0AAfTHCIApJoykqCoNIAAlMYuEbB4AIEGBAJQFA4ARGxu7SJsSYAmnMG4FMShXGiKjGQLwrTzGWOsX4uJKg5DNIqZ7FwGFgDYEIMM8RXgZqnDUXgTR2jdGYndgKJZ0RVkTPYtYma2p7HIiWJgAA7nAJx4hgCSHcWwQ0XjSA+L6jAAJcSbnkFYFUgUqVqm1JCYgJpEB4CyFxNge52AMLQpACaaxMBzlWMwHEmpNggA)

**Expected behavior**

I expect that a call to `room.getStorage()` should succeed immediately after creating and initializing the room.

**Environment (please complete the following information):**

This is a Room with no existing document and no schema (essentially blank/new room)

@liveblocks/core@1.11.0
Google Chrome: Version 123.0.6312.87 (Official Build) (arm64)

**Comment by nvie** [comment]
From this error

```
TypeError: Converting circular structure to JSON --> 
  starting at object with constructor '_LiveList' | property '_items' -> 
    object with constructor 'Array' | index 0 -> 
      object with constructor '_LiveRegister' | property '_parent' -> 
        object with constructor 'Object' --- property 'node' closes the circle at JSON.stringify (<anonymous>) at ...
```

it looks like it's somehow trying to call `JSON.stringify()` on a `LiveList` instance, which should never be happening. It looks like for some reason, the `LiveList` isn't recognized as such. Could you share a full example that would allow us to replicate the issue?

Also, can you check that all versions of your Liveblocks packages are on the same version? You can check with `npm ls`.

**Comment by oravecz** [comment]
It must be caused by some debug logging I have enabled. Closing issue.
