### ISSUE TITLE
Using an async call in an event handler

### ISSUE THREAD

**Issue by oravecz** [liveblocks/liveblocks#1569]
This should be a pretty common situation.

When receiving an event update (e.g. subscribing to Storage updates), I need to execute an asynchronous function within my code base.

```ts
const unsubscribeUpdates = room.subscribe(root, async (root) => {
  debugLog(`Room (${room.id}) applying updates`);
  try {
    await updateValues(...)
  } catch (e) {
    await rebuildValues(...);
  }
});
```

However the  event handler is not allowed to specify the `async` keyword.

Is it considered a best practice to wrap and ignore/workaround the lint/ts problems like so?

```ts
const unsubscribeUpdates = room.subscribe(root, (root) => {
  const update = async () => {
      debugLog(`Room (${room.id}) applying updates`);
      try {
        await updateValues(...)
      } catch (e) {
        await rebuildValues(...);
      }
  };

  void update();
});
```

**Comment by nvie** [comment]
Yeah, this should be fine as long as your `updateValues()` and `rebuildValues()` async functions support being called in parallel, this is currently your responsibility. The `.subscribe()` API is naturally a synchronous API, so with many quick updates, it's possible that the code will get executed in the following order:

1. Incoming change 1, calls `updateValues(1)`
2. Incoming change 2, calls `updateValues(2)`
3. Incoming change 3, calls `updateValues(3)`
4. `updateValues(1)` finishes
5. `updateValues(2)` fails, calls `rebuildValues(2)`
6. `updateValues(3)` finishes
7. `rebuildValues(2)` finishes

If the order of incoming updates is absolutely critical to your functions, and these incoming changes must get handled serially, awaiting each update before taking on the next one, then you can look into solutions like the ones offered by a package like [`async-mutex`](https://www.npmjs.com/package/async-mutex).

For example:

```ts
import { Mutex } from 'async-mutex';

const myMutex = new Mutex();

const unsubscribeUpdates = room.subscribe(root, (root) => {
  void myMutex.runExclusive(async () => {
      debugLog(`Room (${room.id}) applying updates`);
      try {
        await updateValues(...)
      } catch (e) {
        await rebuildValues(...);
      }
  });
});
```

Effectively this will form a "queue" for all the incoming updates, which will guarantee serial execution, but may come at a performance penalty if the processing won't happen fast enough. These are trade-offs you can make for your own situation.

Please let me know if this answers your question. If not, feel free to re-open this issue, and I'm happy to provide more help.
