### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rudi-c** [liveblocks/liveblocks#1576]
**Describe the bug**

Creating too many operations in the same batch causes a StackOverflow.

```
chunk-FIWHKEWT.js?v=26e7ff9a:5987 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at dispatchOps (chunk-FIWHKEWT.js?v=26e7ff9a:5987:38)
    at chunk-FIWHKEWT.js?v=26e7ff9a:6145:11
    at doNotBatchUpdates (chunk-FIWHKEWT.js?v=26e7ff9a:5191:37)
    at Object.batch (chunk-FIWHKEWT.js?v=26e7ff9a:6123:5)
    at index.ts:303:16
    at Object.modifyElementStore (DocumentStore.ts:717:5)
    at modifyElementStore (storeEditing.ts:42:41)
    at createSiteContextExtrusions (getSiteContext.ts:526:3)
    at loadLocationData.ts:346:5
    at liveblocksBatch (liveblocks.ts:132:3)
```

Our use case is that we're importing map data and creating a new object for every building within a 1 square mile area of Manhattan.

It appears that the problem is that `context.buffer.storageOperations.push(...ops);` causes `ops` to put at least as many pointers as the size of `ops` on the JS stack, which is much smaller than the heap.

**Expected behavior**

I would guess that Liveblocks can handle a large message if we don't use array spread. E.g. the following should work:

```
for (const op of ops) {
  context.buffer.storageOperations.push(op);
}
```

I'm not sure what's the best way to handle this. It would be reasonable for Liveblocks to impose a message limit, but what should be the behavior when that happens? Would we still throw and require the user to handle the exception? This limit should be documented.

In any case, a custom exception would be better than a stackoverflow exception.

**Environment (please complete the following information):**

@liveblocks/client 1.9.7

**Comment by nvie** [comment]
@rudi-c This fix is released now in [v1.11.3](https://github.com/liveblocks/liveblocks/releases/tag/v1.11.3). Thanks for reporting!
