### ISSUE TITLE
Verify untrusted inputs in client code

### ISSUE THREAD

**Issue by nvie** [liveblocks/liveblocks#162]
As partially addressed in https://github.com/liveblocks/liveblocks/pull/161, we should verify all untrusted inputs coming in from the outside, like all WebSocket messages that we receive, before using them. Not doing so has the risk that our TypeScript annotations (aka assumptions) don't match the values at runtime.

For large object structures like the `ServerMessage` type, for example, these validation conditionals can become pretty unwieldy if you use simple `if`-statements for them, but we might be able to use a validation library for this. This is exactly the use case that I wrote https://github.com/nvie/decoders for.

Are we open to using it, or vendoring-in a subset of it? (Since it's fully tree-shakable, it would only add the minimum amount of overhead to the bundle.) Would love to discuss!

**Comment by GuillaumeSalles** [comment]
I believe that validating WebSocket messages from our server is not necessary as they're coming from a trusted source. It would impact the performance of a hot path and would likely get in our way when making the WS protocol evolve (backward compatibility).

What do you think now that you have more context on this? @nvie

**Comment by nvie** [comment]
Agreed, we can close this one 👍
