### ISSUE TITLE
[BUG] New TypeScript data types require string index signature when using interfaces

### ISSUE THREAD

**Issue by a-type** [liveblocks/liveblocks#166]
**Describe the bug**

When defining expected types for my Liveblocks storage data using interfaces, the typing system requires me to implement a generic ` { [key: string]: any }` on every object type to satisfy type constraints.

```
2344: Type 'TDAsset' does not satisfy the constraint 'Lson'.
  Type 'TDImageAsset' is not assignable to type 'Lson'.
    Type 'TDImageAsset' is not assignable to type 'JsonObject'.
      Index signature is missing in type 'TDImageAsset'.
```

**To Reproduce**

[Live example](https://www.typescriptlang.org/play?module=1&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgGWANwKYHkBGArDAYxgBoV0NUBneAXzgDMoIQ4ByAAQBsKcuJCAayoB6QjwwA7GGwDcAKHnBpGKAwCGhDHABKGAsQwATAMox1MDAEkVazdoTy4zxhAgAudjnVQ582ooYAB6QsHAwAJ5g2noGlqYw0OoA5hhmFtoAvOSYuHEAPLFE8emWNpZ2WgB8CvKR0XAAgoRaYCXmlgAqUVmITi4Mbp5s3r7+gSHQ8PXaza3tSamlvai5+MX5cxhtxsvd0TVAA)

**Expected behavior**

Interfaces should behave equivalently to types for the purposes of typechecking storage data.

**Illustrations**

**Environment (please complete the following information):**

- `@liveblocks/client@0.16.0`

**Additional context**

Workarounds are available for my own code (i.e. change all `interface` to `type`), but not for library code (like the example from TLDraw).

I'm not honestly sure why types and interfaces differ in this way. It may not be trivial to implement the Lson typings to accommodate the difference. But it is important to be able to, for example, pass the shape of a TLDraw as a type constraint for Liveblocks data (and a TLDraw shape is a deeply nested recursive interface).

**Comment by a-type** [comment]
[That gives me an idea to incorporate it into the library typings](https://www.typescriptlang.org/play?module=1&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgGWANwKYHkBGArDAYxgBoV0NUBnUlKiAO1wOLgF84AzKCEOAcgACAGwo5hEQgGsqAekKiMDGPwDcAKHXBlGKJwCGhDHABq+0QBMAkjr2HjCdXGdcIEAFwCc+qGvVtNWVk4NHNgCzhtGF0DIzgLfRh9SKo4KAwWaIiAd2AYAAs4bypgQjhRHCgfAE84GGqwDHUMAA9IWDqG4wAlDKIsgGUYaH0AcwwhxOMAXnJMZn6AHjNLG2i7IwA+DXUguDAAV2FhSIZT9diMAFpN+sa4QkZMWF11O+MAMR4QNZj7RYAKps4LMAXBWtEGBZUh8DgxiMBGHAAPxwMGeJAAbQA0qc4FIMNUIJw0QBdTwAnGk9gaPbAEnJR4MZ5ZODjBi6UpwKiJYBUTjADCpZD0Jj4fpkdL0YSYOr5YxMlkYCLPEqMAB0u2C9LgDAgDyeujVZx5MD5AqFkqFEBlxkxHOepLeXTgAEEqCLGIDgaDwS1IdC6IwFqxUei4F9eL8NhhvX6A8LRSH4KjIz9bJc454HbodnSGQbmUbEWdhkGxZk4MS5cZ2Zyyq0+TAqGQDlRjAVEq4oDW4Fr4olkndtKN1VWCrpcu20tbbbqMM9VJF4IR9Ax+PAcMY28rNe84AAFXQgPklTCoebi4hx2YX7BXmCLd2ehje7aBYIT8oUKsPh5r3UIGyIoOy6HI8kKL8oj+IxmjaaB4H3I8oBPGBBmGKpxkmaIQUPY9TwoO9k2WMJrAzex33UJkaG5JJok8ZDUPQkYsLomZEA4fRUjXaodhoKZ1XGGAAAp+E4Nx+AASg-OAAIgP9tH45RgCmcCClks5tFCSwBySTpGn7KUbUwVIy3tBddCdaCYzgAARPlzAkbJlWjS5ECcFxxIgYTJM8HA3GEDA1w0AJ93snljiA5VsPYxiCPPChiPCxyorIi4KI0IA), but I don't think the DX is good enough as a solution. I don't know of a way to actually cause a rejection type error when passing in a generic which won't convert, and I'm not sure TypeScript provides one. The common pattern is to resolve `never`, but as a library this would probably only confuse users.

I'll utilize the workaround type for now. I'll also link to the [open issue for this in TS](https://github.com/microsoft/TypeScript/issues/15300) in case that ever produces a useful workaround...

**Comment by nvie** [comment]
Hey @a-type! Thanks for that playground and the ideas. This is a tough problem 😓 ! After many attempts at how to structure this, I think I found a simpler solution that still allows you to use your interface definitions without any of those custom type hacks or tricks.

I think the most correct (and simplest) approach would be to let your interfaces extend `JsonObject` (or `LsonObject`) to make them assignable.

Example:

```tsx
interface ValidInterface extends JsonObject {
  //                     ^^^^^^^^^^^^^^^^^^ Just add this!
  foo: string;
}

interface AnotherValidInterface extends LsonObject {
  //                            ^^^^^^^^^^^^^^^^^^ Or use LsonObject…
  foo: string;
  bar: LiveList<string>;
  //   ^^^^^^^^ …if you want to use Live structures as the values
}

// ✅ These now Just Work™
new LiveObject<ValidInterface>({ foo: 'hi' });
new LiveObject<AnotherValidInterface>({ foo: 'hi', bar: new LiveList() });
```

The added benefit is that TypeScript will point you to any keys inside your interface that doesn't have legal JSON contents:

```tsx
interface IncorrectInterface extends JsonObject {
    foo(): boolean;
//  ~~~~~~~~~~~~~~~ ❌ TypeScript now errors at the root cause! 😍
}
```

[Playground](https://www.typescriptlang.org/play?module=1&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgGWANwKYHkBGArDAYxgBoV0NUBnUuAKSogDtcDizlGX8j4BfOADMoEEHADkAAQA2FHNIiEA1lQD0hWRiYxxAbgBQ+4NoxRBAQ0IY4ANXOyAJgEkTZy9YwAPGFodV6XKy8iPpwcKqqYVHRMbFxYQB6SckpcACaEACucITmTHD2jHCZVNYABpzMQcRlcAAWphhkwIJwAJ5ZcADueTCh4ZHxQ8MjcDAQxaXkmADKMFCZxJlQGP7m-jANcGj2masAdP2CEBAAXHA0UMYA5gZ8hsY+blZwACLAVPYKXRjOrhYvLw+Jh+AJVHjEELRY4QAAUAEpzjgTtIMHk7oYmBgutNsBCYAAeOyOFxPAEYAB8sKQMPO4jqwHEcD48IMQA)

Of course, we'll need to document this expectation clearly. What do you think?

**Comment by a-type** [comment]
Unfortunately they're not _my_ interfaces, they come directly from a third party library I can't control (in this case, TLDraw). The code is basically this:

```
import { TDShape } from '@tldraw/tldraw';

const liveShape = new LiveObject<TDShape>(...);
```

It sucks because there's no real way to tell what's an interface or not when importing types from other libraries, so it all becomes a leaky abstraction.

The interface conversion type also has to be recursive, like so:

```
type FromInterface<T> = T extends Function
  ? T
  : { [K in keyof T]: FromInterface<T[K]> };
```

That kind of type would probably be difficult for someone new to TS to invent. I'm wondering if it might not be worthwhile at this point to export that type as a utility from the library and provide a troubleshooting tip which clearly states you should run your type through the utility if you get an `Index signature is missing` error. Unless the problem can be solved in the typings themselves, I don't think there's a simpler userland solution.

**Comment by nvie** [comment]
We've posted an official [troubleshooting tip](https://liveblocks.io/docs/guides/limits#lson-constraint-and-interfaces) for this issue in our documentation. Thank you for flagging this!

**Comment by gsimone** [comment]
https://liveblocks.io/docs/guides/troubleshooting#lson-constraint-and-interfaces

Updated link ☝️
