### ISSUE TITLE
Tiptap example error breaks Liveblocks connection

### ISSUE THREAD

**Issue by Jkense** [liveblocks/liveblocks#1798]
**Describe the bug**

It seems that there is an error breaking all functionality that Liveblocks provides in the Tiptap & Nextjs example. The Liveblocks editor shows no new entries/changes to the Yjs doc. I am getting the following error:

`Error: Unexpected content type in insert operation`

**To Reproduce**

1. Clone and install current example/nextjs-yjs-tiptap
2. Run` npm run dev` and edit text, view logs

**Expected behavior**

No error

**Illustrations**

Here is picture:

![image](https://github.com/liveblocks/liveblocks/assets/44931777/c0fa45f6-daa0-49c2-b9bd-ab746d919d27)

**Environment (please complete the following information):**

- Same as package.json in example:
   "@liveblocks/client": "^2.0.3",
    "@liveblocks/node": "^2.0.3",
    "@liveblocks/react": "^2.0.3",
    "@liveblocks/yjs": "^2.0.3",
    "@tiptap/extension-collaboration": "^2.0.4",
    "@tiptap/extension-collaboration-cursor": "^2.0.4",
    "@tiptap/pm": "^2.0.4",
    "@tiptap/react": "^2.0.4",
    "@tiptap/starter-kit": "^2.0.4",
    "@types/node": "^20.3.1",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.2.5",
    "next": "^13.5.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "yjs": "^13.6.7"

**Additional context**

I first encountered the problem in my own project. It seems that it might be a problem that lies with Tiptap, because removing the Collaboration & Collaboration Cursor extension removes the error. Another error that seems to pop up in my terminal is:

`Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438`

This problem seems to be related to SSR in next, and I am not sure if this also has to do with the error above. Any help would be appreciated!

**Comment by Jkense** [comment]
Any updates?

**Comment by jrowny** [comment]
We now have a TipTap extension, @liveblocks/react-tiptap that we recommend for implementing TipTap.
