### ISSUE TITLE
Set Function Not Working As Inteneded

### ISSUE THREAD

**Issue by NikhilRW** [liveblocks/liveblocks#1851]
**canvasObjects.set is not a function**

The Set Function Is Not Available For canvasObjects Type of LiveMap<string,any>

**To Reproduce**
1. Move Any Object On Canvas
2. Mutating the storage using useMutation
3. Error Comes That Set Is Not A Function

**Expected behavior**

The Set Function Should Be Able Used And Set The State Of The Storage At And Should See The Changes After Reloading

**Illustrations**
![Screenshot 2024-07-17 222149](https://github.com/user-attachments/assets/3a5921ee-54ba-4626-8db3-db18bd53bbd0)

**Environment (please complete the following information):**

- Liveblocks packages and packages version    [ "@liveblocks/client": "^2.2.2","@liveblocks/react": "^2.2.2"]
- NextJs Package Version [next: 14.2.5]

**Comment by nvie** [comment]
Hi @NikhilRW, thanks for reporting. Could the `"canvasObjects"` top-level key not be initialized for this room by any chance? It seems like `canvasObjects` is `undefined` here for you, or that `storage.get('canvasObjects')` return something else that isn't a LiveMap like your type annotation seems to suggest.

How are you initializing your room? We suggest doing something like this when you connect to the room:

```ts
<RoomProvider /* ... */
    initialStorage={() => ({ canvasObject: new LiveMap() })}>
  ...
</RoomProvider>
```

**Comment by NikhilRW** [comment]
Thank You Replying I Have Already Used InitialStorage While Using Room Provider
And The Problem Still Persist After Wiping Data From Room Storage. 

~~~jsx
export function Room({ children }: { children: ReactNode }) {
  return (
    <LiveblocksProvider publicApiKey={process.env.NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY!}>
      <RoomProvider
      id="fig-room"
      initialPresence={{ cursor: null, cursorColor: null, editingText: null }}
      initialStorage={{canvasObjects: new LiveMap()}}
    >
      <ClientSideSuspense fallback={<Loader />}>
        {() => children}
      </ClientSideSuspense>
    </RoomProvider>
    </LiveblocksProvider>
  );
}    
~~~  
This Is My Code Am I Doing Something Wrong ?

**Comment by nvie** [comment]
@NikhilRW Your code snippet is looking good, and I don't see any issues with it. Just checking in here to see if you have been able to resolve this problem.
