### ISSUE TITLE
No changelog or release notes for 2.5.2

### ISSUE THREAD

**Issue by BorePlusPlus** [liveblocks/liveblocks#1901]
**What is the improvement or update you wish to see?**
v2.5.2 is on npm for a few days now, but neither changelog nor releases on GitHub mention it. This makes me a bit uncomfortable to upgrade to it.

**Is there any context that might help us understand?**

Nothing special

**Does the docs page already exist? Please link to it.**
- [Changelog public](https://github.com/liveblocks/liveblocks/blob/main/CHANGELOG_PUBLIC.md)
- [Changelog](https://github.com/liveblocks/liveblocks/blob/main/CHANGELOG.md)
- [Releases](https://github.com/liveblocks/liveblocks/releases)

**Comment by marcbouchenoire** [comment]
Hi!

`v2.5.2` contained a new feature so we should have published it as `v2.6.0`, which is out now: https://github.com/liveblocks/liveblocks/releases/tag/v2.6.0.

**Comment by BorePlusPlus** [comment]
OK - thanks for heads up.
