### ISSUE TITLE
 Cannot convert argument to a ByteString because the character at index 19 has a value of 8230 which is greater than 255. This happens when creating a new room

### ISSUE THREAD

**Issue by abubakarakram167** [liveblocks/liveblocks#1909]
Error happened while creating a room: TypeError: Cannot convert argument to a ByteString because the character at index 19 has a value of 8230 which is greater than 255

My code is this and I facing an error in nextjs using clerk, while creating room with liveblocks.

export const createDocument = async ({
	userId,
	email,
}: CreateDocumentParams) => {
	const roomId = nanoid();

	try {
		const metadata = {
			creatorId: userId,
			email,
			title: "Untitled",
		};

		const usersAccesses: RoomAccesses = {
			[email]: ["room:write"],
		};
	
		const room = await liveblocks.createRoom(roomId, {
			metadata,
			usersAccesses,
			defaultAccesses: [],
		});

		console.log("after api endpoint", room);
		revalidatePath("/");

		return parseStringify(room);
	} catch (error) {
		console.log(`Error happened while creating a room: ${error}`);
	}
};

**Comment by nvie** [comment]
Hey @abubakarakram167 – we have seen this issue pop up with a couple of customers using Nextjs, and it looks like this could be related if you have folders/files inside the pages or app router that are named `[[...something]]`. On some OSes, typing `...` three times will convert to the char 8230 (`…`), so the folder/file name is actually `[[…something]]` which is causing issues. This isn't always well-visible, depending on your editor. The way to fix this is to change the folder/file name to use three individual dots instead. Sometimes the way to type these are to type this sequence instead: `.` `.` `.`, then Ctrl+Z (which undoes `…` back to `...`). Hope this helps!

**Comment by abubakarakram167** [comment]
> Hey @abubakarakram167 – we have seen this issue pop up with a couple of customers using Nextjs, and it looks like this could be related if you have folders/files inside the pages or app router that are named `[[...something]]`. On some OSes, typing `...` three times will convert to the char 8230 (`…`), so the folder/file name is actually `[[…something]]` which is causing issues. This isn't always well-visible, depending on your editor. The way to fix this is to change the folder/file name to use three individual dots instead. Sometimes the way to type these is to type this sequence instead: `.` `.` `.`, then Ctrl+Z (which undoes `…` back to `...`). Hope this helps!

Thanks for your response. I have tried both of the above solutions you mentioned, but it didn't work, unfortunately. My directory structure is this using VS code editor on MAC. Image attached below: 

![Screenshot 2024-09-05 at 3 18 15 PM](https://github.com/user-attachments/assets/1b7e63d9-51d5-461a-a9cc-0b5dd2cf180b)

**Comment by Alessandro-Battiato** [comment]
I'm sadly having the same issue!

**Comment by zandyai** [comment]
I am having this problem too

**Comment by nvie** [comment]
I would love to better understand what might be causing this. The Liveblocks node client is "just" trying to make a `fetch()` request, nothing special. In the case of a Nextjs project, this global `fetch()` is likely [patched](https://nextjs.org/docs/app/api-reference/functions/fetch#:\~:text=Next.js%20extends,and%20revalidation%20semantics.), and this patched version is apparently choking while processing some of the request headers (because the `…` character is in there somewhere). Is someone able to provide a bit more information on this, maybe by logging out the request that is being constructed here? Any more information would be highly valuable make sure we get this resolved.

**Comment by Alessandro-Battiato** [comment]
@nvie Thank you for answering! I don't know for sure if the OP is following the same mini-course as mine, but the chunk of code he posted is identical to mine, in fact this is the video: https://www.youtube.com/watch?v=y5vE8y_f_OM&t=62s maybe this can be of help while trying to understand what's going on!

**Comment by jamesmoss** [comment]
I ran into this issue recently and it's a doozy. If you copy and paste the examples from the liveblocks docs, be aware that you need to update the `secret` to use your actually dev or prod key. In the examples the key is truncated for security with the `…` character which is easy to miss but will cause this error. For those wondering, 8230 is the unicode codepoint for `…`.

![CleanShot 2024-10-21 at 16 17 09](https://github.com/user-attachments/assets/2f0d1516-e86d-41c6-8fac-98af1c5cc014)

**Comment by nvie** [comment]
Ah, that explains the issue — thanks for sharing @jamesmoss. I'll update the client to do a validation on this and provide a more helpful error message.

**Comment by nvie** [comment]
Thanks again for letting us know about this!

We just [published version 2.9.2](https://github.com/liveblocks/liveblocks/releases/tag/v2.9.2), which should now provide a much more helpful error message if this happens. In addition we updated our reference docs so the truncated key will be copied in full, not truncated.
