### ISSUE TITLE
Error loading document

### ISSUE THREAD

**Issue by MinhTamNT** [liveblocks/liveblocks#1944]
![image](https://github.com/user-attachments/assets/c63b8ad0-4546-4f09-8e4a-28ebf6d0867c)
 
Help me !.......

**Comment by Richouf95** [comment]
Have the same error

**Comment by MinhTamNT** [comment]
> Have the same error

Do you know how to fix it?

**Comment by SugarDarius** [comment]
Hi @MinhTamNT @Richouf95 👋🏻 

Thanks for reporting the issue 🙏🏻 

We have identified the issue and released a fix a few minutes ago (at 10:00 AM CEST). 
You should now be able to see your storage again and delete it as well. 

Please let us know if everything is good on your side and I will close the issue 🙂

Thanks!
Aurélien

**Comment by Richouf95** [comment]
That's why I currently have access to my data.
Thank you for your efforts

**Comment by SugarDarius** [comment]
Great to hear it! 🙏🏻 
Closing the issue then 🙌🏻
