### ISSUE TITLE
Show deleted objects on StorageUpdate

### ISSUE THREAD

**Issue by sno6** [liveblocks/liveblocks#1965]
**Is your feature request related to a problem? Please describe.**

In my application I have a non-ui related process that needs to run every time my Liveblocks document changes in a certain way. Such as certain LiveObject's being updated, things being pushed and popped from a LiveList, and items being removed from a LiveMap.

My schema is along the lines of:

```
parent: LiveMap
    key: LiveList<LiveObject>
```

To achieve this, I call `room.subscribe` on the highest level map object and run a function that further delineates the changes.

This works well for LiveObjects, and well enough for the LiveMap, however for cases where I am popping from a LiveList I need more information, such as what item was deleted (in my case even knowing the parent would be useful).

There are hacky solutions, such as updating a LiveObject with a tombstone key before removing from the list, but even that has some nuance as it appears if you update an object and then remove it from a list LB is smart enough to ignore the first operation in a batch update.

**Describe the solution you'd like**

The current structure of the update delta is 

```
export type LiveListUpdateDelta =
  | { type: "insert"; index: number; item: Lson }
  | { type: "delete"; index: number }
  | { type: "move"; index: number; previousIndex: number; item: Lson }
  | { type: "set"; index: number; item: Lson };
```

"move" already has "previousIndex", so my suggestion here is that we add "previousItem" or something of that nature to the delete operation. 

**Additional notes**

If the problem and suggested solution above are valid then I am more than happy to create a PR for this.

**Comment by nvie** [comment]
Hey @sno6! I added experimental support for this in #2008. Would you mind giving this implementation a try, and let us know if this solves your problem in a satisfactory way? You can do so by running the following command in your project:

```bash
$ npx create-liveblocks-app@latest --upgrade experimental
```

This should bump all your Liveblocks packages to version `v2.9.3-experimental1` in your project. After doing this, you should see this structure:

```ts
export type LiveListUpdateDelta =
  | { type: "insert"; index: number; item: Lson }
  | { type: "delete"; index: number; deletedItem: Lson }
  //                                 ^^^^^^^^^^^ ✨
  | { type: "move"; index: number; previousIndex: number; item: Lson }
  | { type: "set"; index: number; item: Lson };
```

Would you mind providing your feedback on this?

**Comment by sno6** [comment]
Hey @nvie, appreciate the work you've done here. I've just tested your changes and they work great, this will be very helpful.

Side note: The LiveListUpdateDelta seems to be exported, however I wasn't able to find it under /core. Likely a me/editor issue, just thought I would mention.

**Comment by nvie** [comment]
> Hey @nvie, appreciate the work you've done here. I've just tested your changes and they work great, this will be very helpful.

Happy to make it part of our planned 2.10.0 release in that case. Thanks for confirming!

> Side note: The LiveListUpdateDelta seems to be exported, however I wasn't able to find it under /core. Likely a me/editor issue, just thought I would mention.

You should never (have to) import anything directly from `@liveblocks/core`, because those are considered private APIs only. We can break these at any time. Only the exports from `@liveblocks/client` are considered public API. Are you relying on any `core` exports that aren't available in `client`? If so, please let us know! 🙏
