### ISSUE TITLE
422 when updating metadata with empty string value

### ISSUE THREAD

**Issue by sno6** [liveblocks/liveblocks#1971]
**Describe the bug**

The following error is given when trying to update a metadata key with an empty string value.

```
Value at key 'metadata': Either:
- Must be undefined or null
- Value at key 'color': Either:
  - Must be null
  - Too short. Must be at least 1 characters.
```

**To Reproduce**

1. Create a room and note the id.
2. Call POST https://api.liveblocks.io/v2/rooms/<room_id> with 
```
{
  "metadata": {
    "color": ""
  }
}
```

**Expected behavior**

A response with a status of 200, and an updated metadata with `color` as `""`.

**Context**

One can delete the key from the metadata property but in my case an empty string is a valid value and I don't think Liveblocks should impose data structure limitations on the metadata object.

**Comment by sno6** [comment]
Any update on this @nvie

**Comment by nvie** [comment]
Hey @sno6, I think we forgot to circle this back to you, but we pushed a fix for this two weeks ago (on Oct 9), so you should be able to use this now without issues! 🙏
