### ISSUE TITLE
Peer dependency warnings with @liveblocks/react-lexical and Lexical 0.18.0

### ISSUE THREAD

**Issue by thinkininfinity** [liveblocks/liveblocks#1981]
**Describe the bug**

When initializing a Next.js project with Liveblocks using pnpm, peer dependency warnings are encountered related to `@liveblocks/react-lexical` and Lexical packages. The installed version of Lexical (0.18.0) is newer than the peer dependency requirements of `@liveblocks/react-lexical`.

**To Reproduce**

1. Create a new Next.js project
2. Install Liveblocks and Lexical packages using pnpm
3. Run `pnpm install`
4. Observe the peer dependency warnings

**Expected behavior**

The installation should complete without peer dependency warnings, or there should be a clear way to resolve these warnings without downgrading Lexical.

**Illustrations**

N/A

**Environment (please complete the following information):**

- Liveblocks packages and versions:
  - @liveblocks/client: 2.8.2
  - @liveblocks/react: 2.8.2
  - @liveblocks/react-lexical: 2.8.2
  - @liveblocks/react-ui: 2.8.2
- Lexical packages and versions:
  - lexical: 0.18.0
  - @lexical/react: 0.18.0
- Next.js: 14.2.14
- React: 18.3.1
- React DOM: 18.3.1
- pnpm: 9.11.0

**Additional context**

Here's the exact warning message:

```sh
WARN  Issues with peer dependencies found
.
└─┬ @liveblocks/react-lexical 2.8.2
├── ✕ unmet peer lexical@0.16.1: found 0.18.0
├── ✕ unmet peer @lexical/yjs@0.16.1: found 0.18.0
├── ✕ unmet peer @lexical/react@0.16.1: found 0.18.0
└── ✕ unmet peer @lexical/utils@0.16.1: found 0.18.0
```

Questions:
1. Is it safe to ignore these warnings?
2. If not, what's the recommended way to resolve these peer dependency conflicts?
3. Are there plans to update `@liveblocks/react-lexical` to support Lexical 0.18.0?

**Comment by jrowny** [comment]
Hi there,
Sorry about this, we'll be update this package soon.

1. it's safe to ignore these if you don't see any issues
2. you can also add an overrides section to package.json. In pnpm that looks like this:
```"pnpm": {
    "overrides": {
      "@lexical/react": "0.18.0",
      "@lexical/utils": "0.18.0",
      "@lexical/yjs": "0.18.0",  
      "lexical": "0.18.0" // any other conflicts
    }
  },```
3. Yes, we actually had a problem with 0.16.2, which is why we locked it, but things seem more stable since then. We will update the package soon.
