### ISSUE TITLE
Is it possible to filter notifications by room_id via React Hook

### ISSUE THREAD

**Issue by barbaldo** [liveblocks/liveblocks#1999]
**What is the improvement or update you wish to see?**

Examples on how to filter notifications by room_id with the hook useInboxNotifications()

**Is there any context that might help us understand?**

N / A

**Does the docs page already exist? Please link to it.**

N / A

**Comment by nvie** [comment]
Hi @barbaldo — currently the most reliable way is to use:

```ts
const { inboxNotifications } = useInboxNotifications();
const filteredNotifications = React.useMemo(
  () => inboxNotifications.filter(n => n.roomId === roomId),
  [inboxNotifications, roomId]
);
```
