### ISSUE TITLE
Expose the room Object when using useSelector hook

### ISSUE THREAD

**Issue by captaindev404** [liveblocks/liveblocks#200]
Expose the Room object when using `useSelector` hook.
When using the Zustand package, it is possible to spread `undo` and `redo` functions from the room object: ` const undo = useStore((state) => state.liveblocks.room?.history.undo);` 
`const redo = useStore((state) => state.liveblocks.room?.history.redo);`

When using the Redux package, we have to use `client.getRoom(roomId).history.undo`.

**Comment by GuillaumeSalles** [comment]
We can't expose the room this way because it would break store serialization (necessary to be compatible with redux ecosystem).
