### ISSUE TITLE
Error while resolving a comment on Lexical editor

### ISSUE THREAD

**Issue by barbaldo** [liveblocks/liveblocks#2010]
**Describe the bug**

I implemented the solution outlined in the following docs: https://liveblocks.io/dashboard/LIhWQjZ5InMJbK7118hHZ/projects/66a8c337839b83af7783f27a/quickstart and 
https://liveblocks.io/docs/api-reference/liveblocks-react-lexical#AnchoredThreads it all works pretty well however whenever I solve a thread from inside the editor I get this: Unexpected Application Error!
Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

**To Reproduce**

1. Follow the aforementioned docs 
2. Comment anything
3. try to solve said comment

**Expected behavior**

The thread should just disappear

**Additional context**

As with my previous issues, I may be just using Liveblocks wrong or making a mistake, if that's the case I apologize in advance.

**Comment by jrowny** [comment]
At first glance, I don't think you're using it wrong, I think this may be a bug. We will look into it!

**Comment by barbaldo** [comment]
@jrowny fantastic! If you need any more info hit me up!

**Comment by barbaldo** [comment]
Also I just discovered that the same exact behaviour happens in the following situation:

- I have an editor with text and comments inside
- Ctrl + A to select everyhting
- Delete to delete everything
- Same error outlined in the original thread

This brings me to a question I have, is there a way in Lexical to detect if you're deleting commented text? That would be super useful

**Comment by nimeshnayaju** [comment]
Hey @barbaldo, thank you for the extra reproduction steps. We'll look into this shortly and will reach out if there is more information we may need from you. Thank you for reporting the issue 🙏🏼

**Comment by barbaldo** [comment]
Hey @nimeshnayaju , thanks for looking into it! Is is there any news?

**Comment by barbaldo** [comment]
I'd like to add another situation with the same error, basically if you add text and comments, if you try to resolve a comment from the <AnchoredThreads> (Resolve meaning you click the little check icon) it generates the same error

**Comment by nimeshnayaju** [comment]
Hey @barbaldo, I tried reproducing the steps you outlined but wasn't able to. Do you think you could share a screencast and the error log you see? 


https://github.com/user-attachments/assets/d8ed6a64-a5fd-40b8-801b-2964ade2ef68

**Comment by barbaldo** [comment]
@nimeshnayaju trying to upload a screen recording but github is not collaborating....

**Comment by barbaldo** [comment]
https://github.com/user-attachments/assets/8c0898ea-5695-4d1a-a705-50bcd0f6bab2

**Comment by barbaldo** [comment]
@nimeshnayaju There you go! Just for context I'm using the following packages
"@lexical/react": "^0.16.1",
"lexical": "^0.16.1",
"@liveblocks/react-lexical": "^2.10.2",

**Comment by barbaldo** [comment]
@nimeshnayaju PS: As you've noticed the editor starts with a comment already present, that's because I cannot delete it. I'm attaching a screen cap demonstrating the other way to generate said error.


https://github.com/user-attachments/assets/176e1ab3-c923-484b-a7bc-e0c3c5fb4458

In the recording you can see when I do ctrl + a (everything is highlighed), then hit delete and the error appears.

**Comment by barbaldo** [comment]
@nimeshnayaju Also of note we don't use NextJS, just plain React.

**Comment by nimeshnayaju** [comment]
Hey @barbaldo, would it be possible to share a minimal reproduction with the setup you mentioned? I am trying to reproduce on my end but haven't been successful. This could be related to Lexical too but a reproduction would really help me debug this faster and better! A GitHub repository or a Codesandbox, whichever is convenient for you!

**Comment by barbaldo** [comment]
@nimeshnayaju I'll give it a go and share

**Comment by barbaldo** [comment]
@nimeshnayaju https://github.com/barbaldo/lb_vite_minimal_error

**Comment by nimeshnayaju** [comment]
The reproduction helped a bunch @barbaldo. I've just merged a [fix](https://github.com/liveblocks/liveblocks/pull/2041). Will let you know when the version is released!

**Comment by barbaldo** [comment]
@nimeshnayaju That's wonderful news! I have an additional question, the same issue also happens if I use TipTap instead of Lexical, will this fix solve that as well?

**Comment by nimeshnayaju** [comment]
The fix hasn't been applied to Tiptap yet but thanks for letting us know that this is an issue on Tiptap too. I'll ping @jrowny, who worked on the Tiptap editor about the issue and see if the same fix works.

**Comment by barbaldo** [comment]
Fantastic thanks do you need a basic repo for tiptap too?

**Comment by nimeshnayaju** [comment]
Most likely not. Is it a similar setup as the one for Lexical?

**Comment by barbaldo** [comment]
@nimeshnayaju The exact same described in the quickstart guide. Pure react, so no Next js.
