### ISSUE TITLE
[React + TS + Vite + Pocketbase + BlockNote] - Editor Authentication Documentation

### ISSUE THREAD

**Issue by aleenacares** [liveblocks/liveblocks#2027]
**What is the improvement or update you wish to see?**

I would like to see examples on how to implement the [authentication](https://liveblocks.io/docs/authentication) examples for a client side implementation. Specifically with Vite's React TypeScript implementation. 

I'd also love if there was a way to make it work with [Pocketbase](https://pocketbase.io/) similar to the firebase setup already in the docs.

**Is there any context that might help us understand?**

I'm looking for something I can run through the client side without a "server" attached to it. The examples as they exist show how to call the `liveblocks` API for authentication when we're doing it through the server, but what if we're trying to implement it on client side only?

Is what I'm asking for possible with liveblocks? 

**Does the docs page already exist? Please link to it.**

Linked above as well, but I'm hoping an addition can be added to the following page: [authentication](https://liveblocks.io/docs/authentication)

EDIT: In an earlier iteration of this issue I forgot to mention that I'm interested in the above with the [BlockNote](https://www.blocknotejs.org/) integration

**Comment by jrowny** [comment]
Authentication is not possible purely on the client, as it would not be secure. You can use a public key, but we don't recommend it for production, more just for testing. 

The next release will include experimental offline support for TipTap, which will allow you to edit documents offline and sync them back up. If you want the real time collaboration that Liveblocks provides, you will need to be online. Without a server, your only real option for collaboration is p2p and that's outside the scope of what we offer. There are some pure p2p based options out there, but even those will need some way for users to "find" each other. 

BlockNote is not yet compatible but we are working with BlockNote on compatibility and that will likely come as a customized package from them.
