### ISSUE TITLE
No webhook RoomDeletedEvent when using a GCF to delete a room

### ISSUE THREAD

**Issue by Jkense** [liveblocks/liveblocks#2040]
**Describe the bug**

My webhook does not reflect a room being deleted. I can see my room being removed in the liveblocks dashboard, but the webhook is not called.

I've reconfigured a 'fresh' webhook but the problem persists.

If I test the webhook through the dashboard, it does send an event. If I remove the room manually from my dashboard > rooms it is also called. But from my own backed it is not.

Here is the code that deletes my room:

```
exports.on_layout_delete = onDocumentDeleted(
  "layouts/{layoutId}",
  async (event) => {
    // Delete the room
    const layoutId = event.params.layoutId;
    if (!layoutId) {
      throw new HttpsError("invalid-argument", "Invalid request data");
    }
    return await delete_room(layoutId);
  },
);

```

```
exports.delete_room = async (roomId) => {
  const liveblocks = new Liveblocks({
    secret: process.env.LIVEBLOCKS_SECRET,
  });

  return await liveblocks.deleteRoom(roomId);
};
```

I don't think there is anything wrong with the cloud function itself. I can see the room disappear from the liveblocks dashboard.

I am using a GCF with a firestore trigger. No errors occur in the GCF.

**Environment (please complete the following information):**

- "@liveblocks/node": "^1.10.1" in my GCF

**Comment by nvie** [comment]
Thanks for reporting, we'll have a look at this today! 🙏

**Comment by FlowFlorent** [comment]
Hi @Jkense, you have spotted a bug in our system, very sorry about this!

We will have a fix running tomorrow. 

Thank you for reporting!

**Comment by FlowFlorent** [comment]
Hi @Jkense, the fix is up and running 🙂

**Comment by Jkense** [comment]
Just tested and it seems to be solved. Thank you! 🙏
