### ISSUE TITLE
Unclear how to leverage TipTap as Text editor

### ISSUE THREAD

**Issue by barbaldo** [liveblocks/liveblocks#2046]
Really cool to see that now you can use TipTap as the TextEditor. However it's unclear from the documentation how that data can be accessed in the backend. I mean, with Lexical there's a package called node/lexical, is there supposed to be something similar with TipTap or should we just use realtime APIS?

**Comment by haydenbleasel** [comment]
@CTNicholas just finished merging a new @liveblocks/tiptap extension, I imagine once it's all polished up post-merge it'll become available.

**Comment by barbaldo** [comment]
@haydenbleasel That sounds amazing, is there a timeline on that?

**Comment by barbaldo** [comment]
@haydenbleasel Other question, now that the package isn't out yet, is there a way to get the data on the server in another way? I've tried to use @liveblocks/node with getYjsDocument() and it spits out something like this.

`{
  root: '[object Object]asd[object Object]asd[object Object]asd[object Object]asd[object Object]asd',
  default: '<paragraph><highlight>Ciao</highlight></paragraph><paragraph><bold>Bold</bold></paragraph><paragraph><italic>Italics</italic></paragraph><heading level="2"><highlight><strike>Title</strike></highlight></heading><paragraph><footnotereference class="footnote-ref" data-id="1542c179-33dc-4fa8-b163-c3b991fa306e" referenceNumber="1"></footnotereference>ciao</paragraph><footnotes class="footnotes"><footnote data-id="1542c179-33dc-4fa8-b163-c3b991fa306e" id="fn:1"><paragraph>nota</paragraph></footnote></footnotes>'
}`

What format is this? Also why the "root" property is badly formatted javascript?

**Comment by haydenbleasel** [comment]
@barbaldo I would wager it'll be released within the next few weeks, but I'm just a Liveblocks stalker and not on the team so better wait for Chris to confirm lol.

**Comment by barbaldo** [comment]
@haydenbleasel Ah I see, thanks anyway. Any clue as to my other questions?

**Comment by CTNicholas** [comment]
Thanks for helping out @haydenbleasel! We just merged this a couple of days ago and haven't announced it yet @barbaldo. We're working on a Node.js package right now, and hope to have it soon. Sit tight!

You're seeing `[object Object]` as this is all the info we can provide with this API. I'd recommend following [this guide](https://liveblocks.io/docs/guides/getting-tiptap-state-on-the-server) to get your Tiptap state on the server. If this doesn't work with our new package, don't worry, as we have an official package coming soon.

**Comment by barbaldo** [comment]
That's some wonderful news! Thanks for the guide I'll give it a go right now, just making sure I'm not mistaken: yDocToProsemirrorJSON() gets the doc in a shape that's understandable by TipTap? Understandable in such a way that could be turned into HTML with this https://tiptap.dev/docs/editor/api/utilities/html#generating-html-from-json ?

Again thanks for the quick update y'all are wonderful!

**Comment by barbaldo** [comment]
@CTNicholas Question: is it possible to have more than one editor per room or do you recommend creating more than one room if that's needed?

**Comment by CTNicholas** [comment]
> That's some wonderful news! Thanks for the guide I'll give it a go right now, just making sure I'm not mistaken: `yDocToProsemirrorJSON()` gets the doc in a shape that's understandable by TipTap? Understandable in such a way that could be turned into HTML with this https://tiptap.dev/docs/editor/api/utilities/html#generating-html-from-json ?

Yes, I believe so!

> @CTNicholas Question: is it possible to have more than one editor per room or do you recommend creating more than one room if that's needed?

We generally recommend one room per page—you can have multiple Tiptap editors on one page. Bear in mind we haven't fully released our package yet, and some components (e.g. AnchoredThreads) may not support multiple editors yet.

**Comment by barbaldo** [comment]
@CTNicholas I see that's fair, we'll go with one room per editor then figure it out from there. Thanks!

**Comment by CTNicholas** [comment]
> @CTNicholas I see that's fair, we'll go with one room per editor then figure it out from there. Thanks!

Sorry, I mistyped! 

- You can have multiple Tiptap editors per room, and that's fine.
- There might just be some bugs as we haven't released it yet. 
- Generally avoid multiple rooms per page, as each adds a lot of memory overhead.

**Comment by barbaldo** [comment]
Oh! Then I misunderstood. But it still answers my question, the thing is we have a weird use case. Anyway really I was asking because I noticed that for every editor, the YFragment shows up as default, and I figured that by having multiple editors we'd run into conflicts for that.

**Comment by jrowny** [comment]
fyi, we now have a node/prosemirror package that can modify and read data from TipTap, but we don't have documentation just yet, but there are tests in the package that show how to use it and it's very similar to the Lexical package.

As per multiple-editor support, the next release will support passing in a "field" name into the `useLiveblocksExtension` hook, as long as it's unique, you can have more than one editor per page. This will be a breaking change from before where it was done inside `liveblocksExtension.configure`. We decided to move it so we could have all the configuration in one place.

**Comment by jrowny** [comment]
I'm going to close this issue as I think everything here is resolved,  please feel free to open a new one if you have any questions.
