### ISSUE TITLE
react-tiptap: FloatingComposer onComposerSubmit prop not working

### ISSUE THREAD

**Issue by Ecaratti** [liveblocks/liveblocks#2065]
**Describe the bug**

Passing onComposerSubmit as prop to the FloatingComposer element of the @lexical/react-tiptap package does nothing.

**Proposed fix**

Looks like the prop isn't used at all in the [source file](https://github.com/liveblocks/liveblocks/blob/main/packages/liveblocks-react-tiptap/src/comments/FloatingComposer.tsx) of the FloatingComposer.

Looking at the implementation in @lexical/react-lexical, I suggest adding ` props.onComposerSubmit?.(comment, event);` to the handleComposerSubmit function: 

```typescript
  const handleComposerSubmit = useCallback(
    (comment: ComposerSubmitComment, event: FormEvent<HTMLFormElement>) => {
      const { body } = comment;
      if (!editor) {
        return;
      }
      props.onComposerSubmit?.(comment, event);
      if (event.defaultPrevented) return //straight from @lexical/react-lexical
      event.preventDefault();

      const thread = createThread({
        body,
      });
      editor.commands.addComment(thread.id);
    },
    [editor, createThread]
  );
```

**Comment by jrowny** [comment]
Thanks for the report. We definitely need to abstract out the stuff that's duplicated between Lexical/TipTap so we don't keep getting diverging functionality. For now, I'll go ahead and update the component, which is also missing attachements/metadata support and we'll make a plan for anchored threads, floating composer, and floating threads to be core components in the react-ui package.
