### ISSUE TITLE
Getting error on using useEditorStatus with Next 15 app

### ISSUE THREAD

**Issue by hbole** [liveblocks/liveblocks#2068]
I am using lexical/react to make a normal editor app, everything is working smoothly when I integrated the room with liveblock for lexical. But when I am trying to get the status, I am getting an error for that specific hook.
It says TypeError: Cannot read properties of undefined (reading 'getProvider')

**Steps to reproduce the behavior:**
1. Setup live blocks as per the doc
2. Setup the editor for lexical and add room
3. add useEditorStatus() call in the component.

**Expected behavior**
Expected to get the statuses

**Illustrations**
<img width="1228" alt="Screenshot 2024-11-14 at 8 52 16 PM" src="https://github.com/user-attachments/assets/ed8d7562-9efb-42b0-8a6e-8e6ad711eca1">

**Environment:**

- Liveblocks packages and packages version
   "@liveblocks/client": "^2.11.0",
    "@liveblocks/node": "^2.11.0",
    "@liveblocks/react": "^2.11.0",
    "@liveblocks/react-lexical": "^2.11.1",
    "@liveblocks/react-ui": "^2.11.0",
- Browser's version:
   Chrome Version 130.0.6723.117

**Comment by nvie** [comment]
I think you may have some different versions of some of our packages. It's important that all `@liveblocks/*` packages are always on the exact same version. You can run the following command that will enforce this for you: `npx create-liveblocks-app@latest --upgrade`.

If you run this command and the problem remains, please let us know and don't hesitate to reopen this issue! 🙏

**Comment by hbole** [comment]
Ok this works, but I had to downgrade both next js versions and react versions for this to work.
Not sure how other things were working earlier.

**Comment by nvie** [comment]
That should not be necessary. Can you share what exact error you ran into, and which versions of React and/or Next.js don’t work for you? Thank you!

**Comment by hbole** [comment]
Older versions of packages:
`"@liveblocks/client": "^2.11.0",`
`"@liveblocks/node": "^2.11.0",`
`"@liveblocks/react": "^2.11.0",`
`"@liveblocks/react-lexical": "^2.11.0",`
`"@liveblocks/react-ui": "^2.11.0",`
`"next": "15.0.2",`
`"react": "19.0.0-rc-02c0e824-20241028"`
`"react-dom": "19.0.0-rc-02c0e824-20241028"`

Current versions:
`"@liveblocks/client": "^2.12.0",`
`"@liveblocks/node": "^2.12.0",`
`"@liveblocks/react": "^2.12.0",`
`"@liveblocks/react-lexical": "^2.12.0",`
`"@liveblocks/react-ui": "^2.12.0",`
`"next": "^14.2.18",`
`"react": "^18"`
`"react-dom": "^18"`
