### ISSUE TITLE
Small typo and missing status in attachment example

### ISSUE THREAD

**Issue by PabloCorso** [liveblocks/liveblocks#2113]
Hi 👋  I was going through the documentation, and I noticed a couple of things:

- The `attachment` here does not have a `status` field? (solved: was not checking for `attachment.type === 'localAttachment'`)
- Typo: missing closing parentheses `)` at the end to close the map function. 

https://github.com/liveblocks/liveblocks/blob/d00b709c446882e3c3d9e2fa9f38333177da1b5f/docs/pages/api-reference/liveblocks-react-ui.mdx?plain=1#L1498-L1501

Thanks for the great work!

**Comment by PabloCorso** [comment]
Oh I see now in the types that `CommentAttachment` doesn't but `CommentLocalAttachment` does define `status`, that's why I was not seing it.

```tsx
declare type CommentMixedAttachment = CommentAttachment | CommentLocalAttachment;
```

**Comment by nvie** [comment]
Ah, great – thanks for catching that typo, @PabloCorso – we'll get that fixed 🙏. Feel free to re-open this PR if you have any follow-up questions about the types, but it sounds like you figured it out!
