### ISSUE TITLE
Error:   × The "use client" directive must be placed before other expressions. 

### ISSUE THREAD

**Issue by Topskys** [liveblocks/liveblocks#2137]
**Describe the bug**

Error:   × The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.
    ╭─[D:\project\temp\office-docs\node_modules\.pnpm\@liveblocks+react-ui@2.15.0_@types+react-dom@18.3.5_@types+react@18.3.16__@types+react@18.3.1_wv4hmuujpstn733227fwmkd5bq\node_modules\@liveblocks\react-ui\dist\components\InboxNotification.mjs:27:1]
 24 │ import { User } from './internal/User.mjs';
 25 │ import { DropdownMenuTrigger } from '@radix-ui/react-dropdown-menu';
 26 │
 27 │ "use client";
    · ─────────────
 28 │ const InboxNotificationLayout = forwardRef(
 29 │   ({
 30 │     inboxNotification,
    ╰────

Import trace for requested module:
./node_modules/.pnpm/@liveblocks+react-ui@2.15.0_@types+react-dom@18.3.5_@types+react@18.3.16__@types+react@18.3.1_wv4hmuujpstn733227fwmkd5bq/node_modules/@liveblocks/react-ui/dist/components/InboxNotification.mjs
./node_modules/.pnpm/@liveblocks+react-ui@2.15.0_@types+react-dom@18.3.5_@types+react@18.3.16__@types+react@18.3.1_wv4hmuujpstn733227fwmkd5bq/node_modules/@liveblocks/react-ui/dist/index.mjs
./node_modules/.pnpm/@liveblocks+react-tiptap@2.15.0_vekif4phk36ykww2fottbnsbhi/node_modules/@liveblocks/react-tiptap/dist/comments/AnchoredThreads.mjs   
./node_modules/.pnpm/@liveblocks+react-tiptap@2.15.0_vekif4phk36ykww2fottbnsbhi/node_modules/@liveblocks/react-tiptap/dist/index.mjs
./src/app/documents/[documentId]/editor.tsx
 GET /documents/j573hz2qmwt4c2zygknw74af6d76z5m3 500 in 28ms

**Application Version**
next.js@15.0.3
react@19

![image](https://github.com/user-attachments/assets/0aed04a4-aada-432b-a94a-172d68036246)

**Comment by indraprasth0** [comment]
⨯ ./node_modules/@liveblocks/react-ui/dist/components/Composer.mjs
Error:   × The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.
    ╭─[C:\Users\DELL\Desktop\school_project\demo_project\googledoc\docs\node_modules\@liveblocks\react-ui\dist\components\Composer.mjs:32:1]
 29 │ import { PopoverTrigger } from '@radix-ui/react-popover';
 30 │ import { TooltipProvider } from '@radix-ui/react-tooltip';
 31 │
 32 │ "use client";
    · ─────────────
 33 │ function ComposerInsertMentionEditorAction({
 34 │   label,
 35 │   tooltipLabel,
    ╰────

Import trace for requested module:
./node_modules/@liveblocks/react-ui/dist/components/Composer.mjs
./node_modules/@liveblocks/react-ui/dist/index.mjs
./node_modules/@liveblocks/react-tiptap/dist/comments/AnchoredThreads.mjs
./node_modules/@liveblocks/react-tiptap/dist/index.mjs
./src/app/documents/editor.tsx
 GET /documents/j97ejjqz1e8q5yg3hq3jmfakth76xet2 500 in 30193ms
 GET /documents/j97ejjqz1e8q5yg3hq3jmfakth76xet2 500 in 173ms
 GET /documents/j97ejjqz1e8q5yg3hq3jmfakth76xet2 500 in 29ms
 GET /documents/j97ejjqz1e8q5yg3hq3jmfakth76xet2 500 in 57ms


**same issue with mi**

**Comment by manascb1344** [comment]
I also faced this issue
A temporary solution to fix this is:

```
const fs = require("fs");
const path = require("path");

// Path to the directory containing Liveblocks components
const directoryPath = path.resolve(
	__dirname,
	"../node_modules/@liveblocks/react-ui/dist/components"
);

// Helper function to process files
const fixUseClient = (filePath) => {
	console.log(`Processing: ${filePath}`);
	const content = fs.readFileSync(filePath, "utf8");

	// Check if the file contains "use client";
	if (content.includes('"use client";') || content.includes("'use client'")) {
		const lines = content.split("\n");

		// Remove "use client"; from its current position
		const filteredLines = lines.filter((line) => line.trim() !== '"use client";');

		// Add "use client"; at the top
		const fixedContent = `"use client";\n` + filteredLines.join("\n");

		// Write the fixed content back to the file
		fs.writeFileSync(filePath, fixedContent, "utf8");
		console.log(`Fixed: ${filePath}`);
	} else {
		console.log(`No 'use client' directive found in: ${filePath}`);
	}
};

// Recursive function to process all JavaScript/TypeScript files in a directory
const processDirectory = (dirPath) => {
	console.log(`Scanning directory: ${dirPath}`);
	const files = fs.readdirSync(dirPath);

	files.forEach((file) => {
		const fullPath = path.join(dirPath, file);

		if (fs.statSync(fullPath).isDirectory()) {
			// Recursively process subdirectories
			processDirectory(fullPath);
		} else if (file.endsWith(".js") || file.endsWith(".mjs")) {
			// Process JavaScript/Module files
			fixUseClient(fullPath);
		} else {
			console.log(`Skipping non-JS file: ${fullPath}`);
		}
	});
};

// Start processing the components directory
console.log(`Starting to process files in: ${directoryPath}`);
processDirectory(directoryPath);
console.log("All files processed successfully.");
```


or else you can add a postbuild in package.json such that it will run automatically before npm run dev or npm start

    "postbuild": "node scripts/patch-liveblocks.js",

**Comment by haseebrj17** [comment]
We could use the @manascb1344 solution but that only works in development env locally.
Here's a reliable solution to the "use client" directive placement issue that works in both local and production environments, without requiring node_modules modifications:

Instead of modifying the package files, create wrapper components that properly implement the "use client" directive. This approach:
- Works consistently in all environments (local, production, Vercel, etc.)
- Follows Next.js best practices for client components
- Doesn't require build-time modifications
- Is easy to maintain

1. Create wrapper components:

```typescript
// components/liveblocks/wrappers.tsx
'use client'

import {
  Comment,
  Composer,
  InboxNotification,
  Thread,
  ThreadList,
  Presence,
  RoomProvider,
  UserMeta
  // Import other Liveblocks components as needed
} from '@liveblocks/react-ui'

export const CommentWrapper = (props: React.ComponentProps<typeof Comment>) => (
  <Comment {...props} />
)

export const ComposerWrapper = (props: React.ComponentProps<typeof Composer>) => (
  <Composer {...props} />
)

export const InboxNotificationWrapper = (props: React.ComponentProps<typeof InboxNotification>) => (
  <InboxNotification {...props} />
)

// Add other components as needed
```

2. Create an index file for easier imports:

```typescript
// components/liveblocks/index.ts
export * from './wrappers'
```

3. Use the wrapped components in your app:

```typescript
// Before:
import { Comment, Composer } from '@liveblocks/react-ui'

// After:
import { CommentWrapper, ComposerWrapper } from '@/components/liveblocks'

const YourComponent = () => {
  return (
    <CommentWrapper
      content="Some comment"
      // ... other props remain the same
    />
  )
}
```

### How it works:

The wrapper solution works because:
1. Our wrapper has the "use client" directive correctly placed at the top
2. When Next.js processes our wrapper component as a client component, everything it imports (including Liveblocks components) is automatically treated as client code
3. The incorrectly placed "use client" directive in the Liveblocks package becomes irrelevant

This is a more reliable solution than modifying node_modules, which can cause issues in production builds and CI/CD pipelines.

Hope this helps! Let me know if you need any clarification.

**Comment by SugarDarius** [comment]
HI everyone 👋🏻  

Thank you for reaching out and reporting this issue 🙏🏻  
We are currently working on a fix. 

I will let you know once it's fixed! 
Thanks!
