### ISSUE TITLE
[BUG] client state / server state flicker

### ISSUE THREAD

**Issue by steveruizok** [liveblocks/liveblocks#270]
**Describe the bug**

Ex: The storage block is getting out of synchronization when resuming my internet connection.
When getting back online, I don't see any changes.

**To Reproduce**

See: https://codesandbox.io/s/romantic-lehmann-z4m8vb

> Click to create a dot, click again and drag to move a dot.

1. Create a LiveMap 
2. Edit the values of the LiveMap rapidly
3. The server state will overwrite the client state

**Expected behavior**

If the update includes a change to data that has since changed on the client (meaning that those changes will have since been sent to the server and so will be part of a future update), then client state should not be overwritten by the incoming server change. Instead, the "optimistic" local data should be preserved.

I understand that this type of behavior is part of the point of using structures like LiveObject (and indeed the fix was to use a LiveMap of LiveObjects instead), see https://codesandbox.io/s/liveblocks-storage-example-txyqvk. However, if it is possible to use heuristics to preserve optimistic changes, I think it would be a huge improvement in the overall flexibility of the library.

**Additional context**

This is especially useful for the case of tldraw, where React components don't individually know about LiveBlocks. Instead, the application expects changes to come in as an array of JSON entries. We subscribe to the LiveMap and, when it changes, push down an update that contains the change. That looks something like this...

```ts
room.subscribe(myLiveMap, () => {
  app.replacePageContent(
      Object.fromEntries(myLiveMap.entries())
    )
})
```

I'm working on a spike where we represent each object with a LiveObject instead, however I'm not sure how this will perform when many objects change at the same time.

**Comment by GuillaumeSalles** [comment]
Hey @steveruizok, that issue fell through the cracks, sorry for not getting back to you sooner. 

Thank you for the detailed report. It completely makes sense to do the same optimization that we do on LiveObject. Working on a fix, it should land on the next release (0.17)
