### ISSUE TITLE
Add a unit test for the bug uncovered by #292

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#293]
https://github.com/liveblocks/liveblocks/pull/292#discussion_r887722211

**Comment by RickyC0626** [comment]
Hey, I noticed that the `.toImmutable()` APIs are preferred over the legacy helper functions. Will the Redux and Zustand packages still use the legacy functions in the near future?

**Comment by nvie** [comment]
> Hey, I noticed that the `.toImmutable()` APIs are preferred over the legacy helper functions. Will the Redux and Zustand packages continue to use the legacy functions in the near future? If so, I'd like to work on this test.

Realistically, yes. I won't have the time to rewrite any of that soon, so you can assume that at least in the next version it will still be using the old/legacy APIs. Really appreciate the help on this! 🙏
