### ISSUE TITLE
Process not defined whilst using client.enter on Observable

### ISSUE THREAD

**Issue by CTNicholas** [liveblocks/liveblocks#297]
This occurs whilst using `client.enter` on [Observable](https://observablehq.com).

```js
// ReferenceError: process is not defined
const room = client.enter("my-room");
```

`@liveblocks/client` is being imported from `https://unpkg.com/@liveblocks/client@0.16.15/index.mjs?module`

https://twitter.com/triptych/status/1533635668772941824/photo/1

**Comment by CTNicholas** [comment]
Adding the following to the first cell in Observable should fix the problem:

```js
globalThis.process = { env: { NODE_ENV: 'production' } }
```

Another possible solution would be using [Skypack](https://www.skypack.dev/view/@liveblocks/client) instead of unpkg:
`https://unpkg.com/@liveblocks/client@0.16.15/index.mjs?module` -> `https://cdn.skypack.dev/@liveblocks/client`

**Comment by triptych** [comment]
It works! 
<img width="425" alt="Screen Shot 2022-06-06 at 10 28 39 AM" src="https://user-images.githubusercontent.com/8691/172213512-b20163ec-3457-4e62-af18-e887811ecfad.png">
