### ISSUE TITLE
Flashing? While performing fast updates.

### ISSUE THREAD

**Issue by steveruizok** [liveblocks/liveblocks#32]
I'm not sure how to describe this one. In an app where I'm making an update to state on each frame, some frames appear to show an older state. In this [example](https://8gplg.csb.app/), this causes a dragging shape will sometimes flash a position from a few frames back. [CodeSandbox here](https://codesandbox.io/s/liveblocks-tldraw-undo-redo-forked-5ree8).

![Kapture 2021-11-13 at 22 56 02](https://user-images.githubusercontent.com/23072548/141661395-88b59785-ecc8-4b35-ae75-42cc0cbf7fd3.gif)

I'm running this on a new MacBook with a >60fps screen, so it could be related? Kind of a torture test, but really this is the old hiccup I've seen.

**Comment by GuillaumeSalles** [comment]
Thanks for the report! I also see it on my 60 fps screen so it's probably on our side. I'll write some stress tests with this specific scenario and I'll get back to you.

**Comment by GuillaumeSalles** [comment]
Fixed on 0.17
