### ISSUE TITLE
Zustand Storage isn't persisting [BUG]

### ISSUE THREAD

**Issue by mmmoli** [liveblocks/liveblocks#328]
**Describe the bug**

Storage doesn't sync to server (liveblocks Dashboard) or any other connected clients.

**To Reproduce**

1. Run `zustand-whiteboard` example (I cloned on [codesandbox](https://codesandbox.io/))
2. Fire-up a few browser tabs.

**Expected behavior**

- Positions of rectangles are synced across browser tabs
- Positions data is visible in liveblocks dashboard

**Illustrations**

Screenshot of independent rectangle positions:
<img width="1144" alt="Screenshot 2022-06-12 at 20 20 00" src="https://user-images.githubusercontent.com/46807/173249758-71c5c6e3-60fd-4515-9c72-7a43d9c1b0aa.png">

Screenshot of empty liveblocks dashboard:
<img width="567" alt="Screenshot 2022-06-12 at 20 21 05" src="https://user-images.githubusercontent.com/46807/173249816-64363fb6-0fd8-4de6-8665-ce11a1646f2c.png">

**Environment (please complete the following information):**

Everything in your Examples
- @liveblocks/client@0.16.9
- https://github.com/liveblocks/liveblocks/blob/main/examples/zustand-whiteboard/package.json#L6-L7

**Additional context**
- I'm trying to pull state out into Zustand/Redux/jotai and getting no luck.
- The React-based examples seem to work fine.
- Same issue in your ["Upgrade examples to 0.16.1" PR](https://github.com/liveblocks/liveblocks/pull/327)

**Comment by vinodsantharam** [comment]
Hi @mmmoli! Sorry to hear that. I have just tried the latest version and 0.16.9. It's working fine. 
Could you please provide your codesandbox's url which contains your not working code? The above link is redirecting to codesandbox's home page.

**Comment by jamesbvaughan** [comment]
I am also unable to get storage to persist with versions 0.17 and above of the zustand package. If I have time this week to put together a codesandbox to demonstrate this, I will.

**Comment by GuillaumeSalles** [comment]
Hello @jamesbvaughan,

We might have introduced a bug on 0.17 that is related to the shape of your storage... If it worked on 0.16, it is still supposed to work on 0.17 so it's on our hands to fix it. Sorry for the inconvenience. 

Just a blind guess, do you have objects with keys as "numbers" in your zustand state? Something like this:

```ts
const key = 0;

const obj = {
  [key]: "value"
}
```

Might not be related at all but asking just in case.

**Comment by jamesbvaughan** [comment]
> do you have objects with keys as "numbers" in your zustand state?

We do not, but we do have a fairly deeply nested object with string UUID keys like `0b0684f4-7805-4668-9bd3-e7c5d82b1b7a`.

**Comment by nvie** [comment]
Hi @mmmoli / @jamesbvaughan! We have been working on adding Zustand v4 support, and have a release candidate ready (`0.19.0-beta0`) that we intend to release later this week. It adds Zustand v4 support, drops Zustand v3 support, and fixes a bug. We also updated/refreshed the [`zustand-whiteboard` example](https://github.com/liveblocks/liveblocks/tree/zustand-v4/examples/zustand-whiteboard).

I haven't been able to reproduce the bug you mentioned here in this bug report yet. Could you do us a favor and see if the latest version fixes this issue for you?

- `npm i zustand@latest`
- `npm i @liveblocks/zustand@beta` (this will install our release candidate `0.19.0-beta0`)
- Make sure to [paste your api key](https://liveblocks.io/dashboard/apikeys) into the `src/store.ts` file

Thank you in advance! 🙏

**Comment by jamesbvaughan** [comment]
Thanks @nvie!

I've started looking in to this upgrade and my main initial feedback is that **it would be really helpful to an example of how to use @liveblocks/zustand with [the zustand slices pattern](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md#slices-pattern)**. Most sizable applications using zustand are likely to be using that pattern, and it makes implementation with types a lot more complicated.

I'm trying to test these upgrades out in our codebase right now, but it's requiring frequent dives into both zustand and liveblocks' source code in order to understand the types, and I still haven't gotten it completely figured out.

For what it's worth though, we restructured our data storage a couple months ago and have not been hitting the bug described in this issue any more. I am not sure what specific change to the shape of our data led to us no longer hitting this bug. Sorry I can't be of more help there!

**Comment by nvie** [comment]
Hi @jamesbvaughan, that's great feedback!

> _"I've started looking in to this upgrade and my main initial feedback is that it would be really helpful to an example of how to use @liveblocks/zustand with [the zustand slices pattern](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md#slices-pattern) and more than one zustand middleware (for example, with subscribeWithSelector). Most sizable applications using zustand are likely to be using that pattern, and it makes implementation with types a lot more complicated."_

I'll think about where to best document this, but that's a great point. For now, we do have an internal test file that uses Zustand's fishes-and-bears slice example, and you can use it as a reference to understand how you can define the slices, and how to annotate your `create()` call.

You can find the standard Zustand setup parts [here](https://github.com/liveblocks/liveblocks/blob/7d2305646f380c7b81edf241a15585806195c641/packages/liveblocks-zustand/test-d/slices.test-d.ts#L10-L44) and [here](https://github.com/liveblocks/liveblocks/blob/7d2305646f380c7b81edf241a15585806195c641/packages/liveblocks-zustand/test-d/slices.test-d.ts#L51-L54). Also, I wrapped this example in a [`subscribeWithSelector`](https://github.com/liveblocks/liveblocks/blob/7d2305646f380c7b81edf241a15585806195c641/packages/liveblocks-zustand/test-d/slices.test-d.ts#L49). The key type annotation to focus on from a Liveblocks perspective is now [this line](https://github.com/liveblocks/liveblocks/blob/7d2305646f380c7b81edf241a15585806195c641/packages/liveblocks-zustand/test-d/slices.test-d.ts#L48):

```ts
const useStore = create<WithLiveblocks<MyState>>()(
  //                                            ^^ Not a typo
  /* ... */
);
```

Key points:

1. Wrap your state type in a `WithLiveblocks<...>` helper, so the type of the `liveblocks` property will be known.
2. Make sure to include that extra empty "call" to `create()(...)`. This is required by Zustand, not Liveblocks, to aid type inference.

Other than this, it should all work automatically. Please let us know if you're running into issues with this.

> I'm trying to test these upgrades out in our codebase right now, but it's requiring frequent dives into both zustand and liveblocks' source code in order to understand the types, and I still haven't gotten it completely figured out.

With this new version, the _only_ place where you should add an annotation is at the `create<T>()(...)` call. There, `T` should be of the form `WithLiveblocks<YourState>`. Once you do that, you should be able to remove all other explicit type annotations from your Zustand and Liveblocks related code. Again, please let us know if there's anything we can help you with.

**Comment by jamesbvaughan** [comment]
> With this new version, the only place where you should add an annotation is at the create<T>()(...) call.

This was the key thing I think I was missing when I first attempted this upgrade yesterday. I had explicit annotations all over the place that (I think) were necessary with the complexity of our use of pre v0.4 zustand and pre v0.18 liveblocks, and now it seems to be working with just that one annotation like you said.

I'll let you know if I run into any other issues!
