### ISSUE TITLE
Couldn't find any versions for "@liveblocks/react" that matches "0.13.0-beta.1"

### ISSUE THREAD

**Issue by dancon** [liveblocks/liveblocks#36]
When I install @liveblocks/react@beta， I got the response as below:

yarn add @liveblocks/react@beta

```
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@liveblocks/react" that matches "0.13.0-beta.1"
? Please choose a version of "@liveblocks/react" from this list: (Use arrow keys)
❯ 0.12.3 
  0.12.2 
  0.12.1 
  0.12.0 
  0.12.0-beta.14 
  0.12.0-beta.13 
  0.12.0-beta.12 
  0.12.0-beta.11 
  0.12.0-beta.10 
  0.12.0-beta.9 
  0.12.0-beta.8 
  0.12.0-beta.7 
  0.12.0-beta.6 
  0.12.0-beta.5 
  0.12.0-beta.4 
  0.12.0-beta.3 
  0.12.0-beta.2 
  0.12.0-beta.1 
  0.11.0 
  0.10.0 
  0.9.0 
  0.8.2 
  0.8.0 
  0.7.3 
  0.7.1 
  0.7.0 
  0.6.0-beta.5 
  0.6.0-beta.4 
```

Installed via npm, `npm i @liveblocks/react@beta` got a similar erro:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @liveblocks/react@0.13.0-beta.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

--- update ---

Figure out it's the problem of my private npm registory.

**Comment by GuillaumeSalles** [comment]
Hi @dancon,

Glad you figured it out! If you're cloning one of our examples, please keep in mind that if they rely on Storage, you will need access to the private beta to run them locally. If you're interested to try out the private beta, please send us an email to hello@liveblocks.io with a brief description of what you're trying to build and we'll add you to the waiting list.
