### ISSUE TITLE
Delete room HTTP API (not just clearing the storage)

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#361]
Provide a way to delete a room from the API and potentially from the dashboard.

Tech design required.
- Should a room be internally archived?
- How does it affect analytics?
- How does it affect querying?

**Comment by adigau** [comment]
New feature request made on Discord: https://discord.com/channels/913109211746009108/913109211746009112/1024414440671690853

**Comment by GuillaumeSalles** [comment]
Done https://liveblocks.io/docs/api-reference/rest-api-endpoints#delete-rooms-roomId
