### ISSUE TITLE
Better storage hooks for @liveblocks/react

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#367]
The goal of this issue is to fix the major drawbacks of `@liveblocks/react` storage hooks.

This will require:
- [ ] Preparing a tech design and presenting it to the team
- [ ] Find a way to collect feedback from the community as early as possible
- [ ] Plan implementation, release and documentation

_**Create additional sub-tasks and link them here to track the overall progress.**_

# Storage hooks drawbacks

## Handling nested data structures is not intuitive

`useList`, `useMap`, `useObject` only let you access direct children of the storage root. 

Let's consider this storage root type:

```typescript
type StorageRoot = {
  child: LiveObject<Child>
}

type Child = {
  grandChild: LiveObject<GrandChild>
}

type GrandChild = {
  x: number
}
```

It's not possible to get `grandChild` with `useObject`. To access `grandChild`, you need to do:

```tsx
function Component() {
  const child = useObject("child");

  if(child == null) {
    return null;
  }

  const grandChild = child.get("grandChild");
}
```

Re-rendering your component when grandChild is changing is even more awkward

```tsx
function Component() {
  const child = useObject("child");

  if(child == null) {
    return null;
  }

  return <OtherComponent grandChild={child.get("grandChild")} />
}

function OtherComponent({ grandChild }) {
  const room = useRoom();
  const [{ x }, setData] = useState(grandChild.toObject());

  useEffect(() => {
    return room.subscribe(grandChild, () => {
       setData(grandChild.toObject());
    });
  }, [room, grandChild]);
}
```

## `useList`, `useObject`, `useMap` return mutable data structures

Our LiveStructures are mutable for performance reasons and to fit better with non-react environments.

This can lead to unintuitive behavior when mixed with react hooks dependencies or `React.memo`.

We had several questions like this one:

```tsx
function Component() {
  const object = useObject("key");
  useEffect(() => {
    // Why is this effect not triggered when `object` is modified??

    // Answer: object is mutable, the reference never changes so this effect will not be triggered
  }, [object]);
}
```

## Re-rendering when a computed value of multiple storage parts has been updated

We need to access the underlying room to achieve this.

```tsx
function Component() {
  const objA = useObject("a");
  const objB = useObject("b");

  const room = useRoom();
  const [computedValue, setComputedValue] = useState();

  useEffect(() => {
    function onChange() {
      setComputedValue(objA.get("x") + objB.get("x"));
    }

    const unsubA = room.subscribe(objA, onChange);
    const unsubB = room.subscribe(objB, onChange);

    return () => {
      unsubA();
      unsubB();
    }
  }, [objA, objB]);
}
```

Re-rendering when a computed value from storage and others' presence has changed, is as difficult.

## Accessing native value attached are the storage root is not possible

```typescript
type StorageRoot = {
  title: string; // This is not accessible using hooks only
  child: LiveObject<Child>
}
```

## All Storage hooks potentially return `null`

All apps need to deal with `useStorage()`, `useList()`, `useMap()`, and `useObject()` potentially returning `null`, and handle those.

```tsx
function Component() {
  const camera = useObject("camera");
  const items = useList("items");

  // 👎
  if (camera == null || items == null) {
    return <div>Still loading...</div>;
  }

  return <MyRealComponent camera={camera} items={items} />
}
```

Components are often structured this way, just so that `Component` deals with the `null` cases for `MyRealComponent`, which contains the important stuff.

This boilerplate is cumbersome and error-prone.

**Comment by nvie** [comment]
Addressed with the launch of 0.18 ✨
