### ISSUE TITLE
Strip `devDependencies` from distributions

### ISSUE THREAD

**Issue by nvie** [liveblocks/liveblocks#399]
We currently copy the contents of `package.json` into the dist folder, but that also copies dev related settings in there that shouldn't live in the outputted bundle per se, like `devDependencies`. We could strip these keys off during the build.

**Comment by GuillaumeSalles** [comment]
To make it extra clean, we can also strip the `scripts` section

**Comment by GuillaumeSalles** [comment]
Zustand is striping even more sections of the package.json

https://github.com/pmndrs/zustand/blob/main/package.json#L80

**Comment by nvie** [comment]
Yeah. Great idea. I’m doing a similar thing in the [decoders build step](https://github.com/nvie/decoders/blob/main/bin/build.sh#L80-L92), too.
