### ISSUE TITLE
Allow authentication to fail

### ISSUE THREAD

**Issue by m1guelpf** [liveblocks/liveblocks#414]
Today, if the call to the authentication endpoint fails, it just keeps getting called forever. However, there are certain use-cases where you might want to handle the exception instead (such as when a user is trying to connect to a room they shouldn't have access to).

In order to make this customizable, we could add an extra key to the client config (`onAuthError`), which gets called with the exception thrown (or the response, if the error is a malformed response), and can return `false` to avoid retries (or anything else to retry anyway).

Digging through the codebase, this seems to be the function I'd add the logic to:

https://github.com/liveblocks/liveblocks/blob/6e5f2189c717426214577b658c838d01543e1001/packages/liveblocks-client/src/room.ts#L855-L863

**Comment by ofoucherot** [comment]
Hello,
You make a good point; we should add a way to customize the logic retry. Your solution makes sense; another solution would be to add a list of error codes that should not retry. We will also have to think about if we want to add customization for the retry delay.
I added a task to our backlog, we will update you when we have a clearer idea on the implementation.

**Comment by npapagna** [comment]
Hi! Just bumped into this issue and I'm checking in to see if there was any progress on this one.

**Comment by TerminalFi** [comment]
Ran into this today. Seems like a much needed capability.

**Comment by basicNew** [comment]
Hi folks! Are there any updates on this one? We would benefit a lot from having this. Thanks!

**Comment by nvie** [comment]
Hello, we have this on our radar. I'm currently thinking about making some changes to holistically improve our client's stability and this would be a natural part of it. It may still take a bit of time before we can publish an updated version, but we're actively thinking about and working on this, so there is progress. We'll report back when we have more information to share — thanks for your patience!
