### ISSUE TITLE
Detect duplicate @liveblocks/client package and mitigate instanceof issues

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#432]
Some [bundlers](https://github.com/liveblocks/liveblocks/pull/98) configurations or mono repo setup duplicate `@liveblocks/client` in the final bundle. It creates bugs that are difficult to identify for our users because we rely on `instanceof` in our code base.

Find a way to mitigate this issue by:
- Detect duplicate `@liveblocks/client` in final bundle (global symbol?) and print an error message that link to specific documentation page
- Remove usage of `instanceof` and use symbol to detect `LiveStructure` (similar to what React is doing I think)

**Comment by nvie** [comment]
I think many library authors struggle with this problem when targeting both CJS and ESM, but I've never seen a reliable detection mechanism for this.

Definitely want to stop relying on `instanceof`, but we still need some kind of oracle to be able to tell whether an incoming object originated from our library one way or the other. Using a unique symbol won't work for the same reason (it's also scoped to the module it's coming from, and thus duplicated). Using a named symbol from the runtime-wide registry (e.g. `Symbol.for()`) may work around the technical issue, but I still think that's only masking the real problem. It would only lead to the "ESM copy" of the bundled code being able to recognize and accept, at runtime, LiveStructure instances that were generated from our "CJS copy" of the bundled code, but that might lead to various wild bugs and broken assumptions elsewhere (deeper down). Stuff like unexpected duplicated memory instances of LiveStructures that should be unique, for example. Or multiple client connections to a room, etc etc.

So I think we should focus on the duplication detection here mostly, and not worry too much about the `instanceof` checks (as it's an unimportant implementation detail).

One hack to detect this situation might be to inject a snippet like this in each of our generated dists:

```ts
if (process.env.NODE_ENV !== "production") {
  const pkg = "@liveblocks/client";
  const format = "ESM";

  const g = globalThis as typeof globalThis & { [key: string]: string };
  if (g && g[pkg] !== format) {
    if (g[pkg] === undefined) {
      g[pkg] = format;
    } else {
      console.warn(
        `${pkg} appears twice in your bundle (as ${g[pkg]} and ${format}). This can lead to hard-to-debug problems. Please see XXX for details.`
      );
    }
  }
}
```

And do a similar thing for all combinations of `@liveblocks/{client,react,redux,zustand,node}` × `{ESM,CJS}`, so emit this code snippet 10 times, with only lines 2 and 3 of this snippet varying.

I'm honestly not sure how I like this hack. I've never seen any other libraries do something like this, even though many libraries out there have similar issues with being bundled multiple times. (As a consumer of libraries, I have in the past struggled with bundler configurations myself, which came to light in similar obscure buggy ways and only made us realize our app's total bundle size was twice what it should be.)

Do you have any other ideas or perhaps a good source to look to for inspiration?
