### ISSUE TITLE
Sending a ws message from the client to the server is limited to 1MB

### ISSUE THREAD

**Issue by ofoucherot** [liveblocks/liveblocks#434]
If the initial storage is big and all the operations needed take more than 1MiB, the websocket message is not going to be sent because of a Cloudflare limitation:
Websocket messages of up to 1 MiB (1048576 bytes). This limit applies to messages received, not sent or proxied through.

We need to split up the operations in multiple messages.

**Comment by nvie** [comment]
This has been addressed in #887, we're testing this out by allowing users to opt-in to the `unstable_fallbackToHTTP` config flag. If these tests are successful, we plan to document this publicly and make it an officially supported feature.
