### ISSUE TITLE
Avoid flash of "others" during reconnect caused by sending "others reset" event after "connection close" event

### ISSUE THREAD

**Issue by ofoucherot** [liveblocks/liveblocks#459]
Feedback from Grant:

> more feedback on event ordering: right now it seems that the client is sending others reset events before updating the room connection state - so the handling of connection close empties the participants list before our code can detect that the connection has dropped.
> 
> we actually want to cache old participants and keep them stable even if liveblocks connection hiccups (which it often seems to for us), so it would be convenient to check room.getConnectionState() inside the others subscriber and have logic based on whether the state is failed which ignores updates. right now we're ignoring reset events instead.

Currently, the others reset event is sent first when the connection closes: [See code](https://github.com/liveblocks/liveblocks/blob/528ff8d3d0d589d0078dddf340c9b22fc655f4f2/packages/liveblocks-client/src/room.ts#L1113). And then the connection state updated event.

---

One way this manifests is by seeing the avatar stack "flash" (others disappearing and reappearing) when the client temporarily is reconnecting. This is unintended behavior indeed. The others in the room should definitely survive such quick reconnections.

Example of the unintended behavior that should be fixed:

https://github.com/liveblocks/liveblocks/assets/83844/b4a37622-d549-44db-a8b3-6500de75b05c

**Comment by nvie** [comment]
Fixed in [1.1.0](https://liveblocks.io/blog/whats-new-in-v1-1).
