### ISSUE TITLE
[BUG] [Zustand|Redux] Sertting undefined value stops sync with Liveblocks

### ISSUE THREAD

**Issue by ofoucherot** [liveblocks/liveblocks#491]
**Describe the bug**

When using the Zustand or Redux integration, adding an undefined value to the state stops the synchronization with Liveblocks server.

Example:
```
set('a', 1) // synced
set('b', undefined) // not synced => expected
set('c', 1) // not synced => not expected
```

**Expected behavior**

The undefined value should be not be synched, but future updates should be.

**Environment:**

- Packages version: tested on 0.17.

**Note**
Undefined is kept in the Zustand state, any further updates call [isJson](https://github.com/liveblocks/liveblocks/blob/528ff8d3d0d589d0078dddf340c9b22fc655f4f2/packages/liveblocks-zustand/src/index.ts#L27) and the state is not synced with Liveblocks since there is an undefined value.

**Comment by rbackman** [comment]
out of curiosity if the second client has a value for b and client a sets it as undefined what would be the expected behaviour? should b dissapear from the second client
