### ISSUE TITLE
Feature request: temporary storage

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#56]
Feature request from @CTNicholas

https://discord.com/channels/913109211746009108/913157273046646795/938057663055560764

______________________

Room storage doesn’t always need to be permanent, in some cases you want the room to reset when all users are offline. Perhaps something like this would be handy, allowing you to erase the current storage when everyone’s gone:
```jsx
<RoomProvider
  onEmpty={storage => {
    storage.clear()
  }
/>

// Or do it automatically:

<RoomProvider
  storage="temporary"
/>
```
______________________

**Comment by GuillaumeSalles** [comment]
That's a great idea! I can imagine a few potential use cases for this:

- Multi player game where you need to delete the storage when the party is over
- Temporary brainstorm on whiteboard
- Liveblocks demo / examples (we're not going to shape our API based on this use case!)

Initial thoughts and related questions that would help us shape the API:

- What are the triggers that would clear the storage? "When no one is the room" might be too aggressive, an unstable connection could clear the storage. Maybe more something "clear the storage after X min/hours/days" of inactivity (similar to a Discord thread).
- Is it something that we want to configure from the front-end and/or the backend?

**Comment by CTNicholas** [comment]
That's a great point about connection loss accidentally clearing storage. When I wrote this, I was considering projects where you will _never_ need to store data after the session is over (such as your multiplayer game use case), so a 5 minute timer after everyone's offline would probably be more than sufficient.

Of course you could also allow the user to choose the amount minutes/seconds before the storage resets.
