### ISSUE TITLE
Feature request: "Match making"

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#57]
Feature request from @CTNicholas

[https://discord.com/channels/913109211746009108/913157273046646795/938057663055560764](https://discord.com/channels/913109211746009108/913157273046646795/938057663055560764)

---

Another handy feature would be a room that automatically generates its own ID, and autofills up to a certain capacity. Once the current room is full, users start filling up a new room. This would be great for public facing pages; Next.js Conf had this feature, with random people's live cursors appearing on screen. It would also be handy for any games built on Liveblocks, as a matchmaking mechanic. Quick example:

```jsx

  matchmaking="busiest"
  prefix="live-cursors-"
  maxUsers={20}
  onCreate={id => {
    // 'live-cursors-cwg3h46shkd4h4hjshs'
    console.log(id)
  }
/>
```

I've written `matchmaking="busiest"` because there could be multiple algorithms for filling the rooms. 
Examples:
`busiest`: When all rooms are full, create a new room. The busiest room is then filled first. 
`emptiest`: When all rooms are full, create a new room. The emptiest room is then filled first.

---

**Comment by andreaselia** [comment]
It would definitely be cool to get some proper examples/functionality down for how to handle this sort of thing when using Liveblocks to create web games.
