### ISSUE TITLE
[FEATURE_REQUEST] Add an endpoint to broadcast an event to a room

### ISSUE THREAD

**Issue by FlowFlorent** [liveblocks/liveblocks#597]
**Is your feature request related to a problem? Please describe.**

Sometimes jobs run in the backend or certain events happen and users would like to be notified. It's currently not possible to broadcast an event external to a room without connecting to it via websocket. This causes issues as the "server connection" to the room will show up as a user in Presence.

Example applications:
- Notify of a new app version and force refresh the app
- Notify when a background job is finished 

**Describe the solution you'd like**

Provide an API endpoint to broadcast and event to a room such as
`POST /rooms/{roomId}/broadcast_event`

```ts
type BroadcastEventBody = {
  type: string;
  [k: string]: any;
};
```

**Comment by sumitngupta** [comment]
Hello!  Our usecase is effectively as a "Fire and forget" from the server to whichever clients might be listening. As you noted, we have long running data importing that we push to a background worker, I'd love to be able to notify when it's complete. 

We can lean on naming conventions to make sure clients are subscribed to the right rooms to get the messages.

**Comment by sahilprasad** [comment]
+1 - this would be huge.

**Comment by FlowFlorent** [comment]
The endpoint is now released! Documentation available here: https://liveblocks.io/docs/api-reference/rest-api-endpoints#post-broadcast-event
