### ISSUE TITLE
Allow multiple clients with different configurations to connect to rooms simultaneously 

### ISSUE THREAD

**Issue by jamesbvaughan** [liveblocks/liveblocks#600]
I'd like to be able to create multiple clients on a single page, each one initialized with different logic in their `authEndpoint` functions, and to have the clients join different rooms at the same time.

For example,
```ts
const clientA = createClient({ authEndpoint: authEndpointFunctionA })
const clientB = createClient({ authEndpoint: authEndpointFunctionB })

// Using zustand
useStoreA.getState().liveblocks.enterRoom(roomA)
useStoreB.getState().liveblocks.enterRoom(roomB)
```

When I try this, I never see a request made to the second auth endpoint.

From a quick look through the client code, I think this might have to do with the auth throttling logic, which (if I understand correctly) is throttling globally rather than per-`createClient`.

I'm working around this in the meantime by waiting to invoke the second `enterRoom` until a 1 second timeout has completed, kind of like this:
```ts
useStoreA.getState().liveblocks.enterRoom(roomA)

setTimeout(() => {
  useStoreB.getState().liveblocks.enterRoom(roomB)
}, 1000)
```

Let me know if I can clarify anything about this issue.

**Comment by GuillaumeSalles** [comment]
Hi @jamesbvaughan,

The auth throttling logic is supposed to be per room. 2 client instances should not impact each other. Which lines of code made you think it was shared? Is it possible that your 2 auth functions are sharing some code that could cause a race condition? I did a quick test with 2 clients and 2 endpoints (no functions, though) in a single app, and it was working properly. Are you able to reproduce this issue with a small example?

Also, I'm curious to know more about what you're trying to achieve with multiple stores/clients? Are you trying to build a real-time dashboard where you can see the other rooms in real time? A bit like Figma dashboard?

**Comment by jamesbvaughan** [comment]
Sorry about the delayed reply here.

I also tried to put together a minimal reproduction and was unable to, and I'm now unable to find the code that made me think that 2 client instances might impact each other.

Feel free to close this issue since it's probably not very actionable, and I can re-open it if I'm able to put together a consistent reproduction that I can share.

As far as our use-case goes, we currently have one Liveblocks room per "project", but we're working on a new feature that will use a project's data, but that we'd like to have separate presence logic for. Doing this by using a second Liveblocks room for this new feature's presence isn't how we intend to have this implemented long-term, but for now it's letting us prototype things rapidly and focus on core features.

**Comment by GuillaumeSalles** [comment]
> I also tried to put together a minimal reproduction and was unable to, and I'm now unable to find the code that made me think that 2 client instances might impact each other.

> Feel free to close this issue since it's probably not very actionable, and I can re-open it if I'm able to put together a consistent reproduction that I can share.

Sounds good! Feel free to reopen it whenever you have an example. Thank you for your answer.
