### ISSUE TITLE
[FEATURE_REQUEST] export `StorageStatus` type

### ISSUE THREAD

**Issue by npapagna** [liveblocks/liveblocks#613]
**Is your feature request related to a problem? Please describe.**

Can the `StorageStatus` type be exported?
This could be useful to type, say, a variable for keeping the previous `storage-status` style.

If the type is not exported, then that variable has to be typed as `string` (or the `StorageStatus` has to be copied & pasted from the package).

**Describe the solution you'd like**

Export tye `StorageStatus` type.

**Additional context**

N/A

**Comment by nvie** [comment]
Great point — yeah, that's annoying. I'll roll a patch release to add it.

**Comment by nvie** [comment]
Thanks for reporting this @npapagna — this is now released as [0.19.5](https://github.com/liveblocks/liveblocks/releases/tag/v0.19.5) 🙏
