### ISSUE TITLE
[FEATURE_REQUEST] Revoke a room access token

### ISSUE THREAD

**Issue by ofoucherot** [liveblocks/liveblocks#615]
**Is your feature request related to a problem? Please describe.**

If a user's access to a room changes (upgraded to room:write or downgraded to room:read), the previous token used to enter the room is still valid for up to one hour.
There should have a way to revoke a token.

**Comment by nvie** [comment]
Granted that every token is a JWT bearer token and possessing one is enough to obtain the permissions it has, the only way I see to actively revoke an unexpired token is to keep an administration of revoked tokens in-memory on the server side (at least until they expire), and check that administration on every request.

Does that match with what you would have in mind for this, too?

**Comment by ofoucherot** [comment]
@nvie Yes it does!
