### ISSUE TITLE
Update the storage / room from the REST API

### ISSUE THREAD

**Issue by captaindev404** [liveblocks/liveblocks#62]
Our HTTP API allows users to initialize, get and delete a room but does not support update scenarios.

In some use cases, users need to mutate the state of a LiveMap, for example, directly from a cloud function or backend environment.

The goal would be to handle storage mutation (LiveObject/LiveMap/LiveList) from a backend environment (cloud functions, nodejs, ...).

Related issue: https://github.com/liveblocks/liveblocks/issues/33 
Discord Message: https://discord.com/channels/913109211746009108/913157273046646795/940963713068957778

**Comment by martolini** [comment]
Alternatively, you could make the client usable in a non-dom environment; something along the lines of this https://github.com/liveblocks/liveblocks/pull/63

**Comment by GuillaumeSalles** [comment]
Can officially be achieved with fetch / WebSocket polyfills in 0.17
