### ISSUE TITLE
[BUG] Undo after a LiveList `set` results in delete/insert events

### ISSUE THREAD

**Issue by plamzd** [liveblocks/liveblocks#628]
**Describe the bug**

We are trying to build multiplayer undo/redo into a collaborative text editor. The editor is, in essence, a sequence of paragraphs (only text) which we store in a LiveList. Whenever a user types some letter into a paragraph the LiveList `set` method is called for the respective element. The issue we are experiencing happens when we invoke `room.history.undo()` too soon after `set` for the same client (e.g. the user clicks ctrl-Z very quickly after typing) - in such cases the local client's room subscription receives 3 updates - a `set` update (which is expected, this is the reverse of our `set`) and then a `delete` and an `insert` for the respective live list element (FWIW, the remote client subscriptions correctly receive only the `set`).

For testing purposes I've added a 1 second delay after the `set` and the `undo` and this only results in a single 'set' event (which is what we'd expect).

**To Reproduce**

Have a single participant in a room. Subscribe for storage updates on the room. Call `undo` immediately after a LiveList `set`. Observe that 3 updates are receives, a `set`, a `delete` and an `insert`.

**Expected behavior**

The undo should reliably produce only a single `set` event that reverses the initial `set`.

**Environment (please complete the following information):**

"@liveblocks/client": "^0.19.4"
"@liveblocks/node": "^0.19.4"
"@liveblocks/react": "^0.19.4
Chrome v108.0.5359

**Comment by GuillaumeSalles** [comment]
Hi @plamzd, 

It definitely look like an issue on our end. We're going to look into it.

**Comment by nvie** [comment]
Hi @plamzd, thanks again for filing this bug report. We have recently fixed two bugs[^1][^2] in this area that might have been related. We haven't been able to reproduce this issue. Would you mind trying to upgrade to the latest version (1.0) to see if these fixes have solved this issue for you? If it's still an issue, please let us know! Thanks! 🙏 

[^1]: https://github.com/liveblocks/liveblocks/pull/636
[^2]: https://github.com/liveblocks/liveblocks/pull/637

**Comment by weiningning** [comment]
I also encountered a similar problem. When I invoke `blocks.insert(child, i)`, and then invoke `blocks.set(i, child)` too soon, in such cases the local client's room subscription receives 2 updates - an insert for the respective live list element and a delete.
![image](https://user-images.githubusercontent.com/20291747/220347216-ef47c8bf-3e7b-4751-8cd8-864f0abd1af8.png)
<img width="989" alt="image" src="https://user-images.githubusercontent.com/20291747/220347329-7eaa8165-0bd4-4bf3-9df0-97f323b1f42f.png">

**Comment by plamzd** [comment]
@nvie Seems like the problem persists with version `1.0.0`:

https://user-images.githubusercontent.com/6538416/220588147-2024906a-2aeb-41be-9a99-b55b2074171c.mov

Here is a demo of me typing a single letter (resulting in a `LiveList#set` operation) and immediately pressing ctrl-Z (a `room.history.undo()`). You can see 3 calls to the local room subscription callback - one with an update, one with a delete and then one with an insert. I've also included a view of the websocket traffic if that helps.

**Comment by nvie** [comment]
@plamzd Thanks again for this bug report, this video was super useful for us to be able to replicate it. We're currently unable to capture it in a unit test, so we need to look into what the underlying issue here can be. Just wanted to mention that we're still looking into it, and we'll try to get a fix out for this soon. Thank you for your patience!
