### ISSUE TITLE
Rooms created with a "/" breaks requests to the dashboard and the HTTP API

### ISSUE THREAD

**Issue by captaindev404** [liveblocks/liveblocks#64]
Rooms created with an id containing `/` breaks the dashboard and the API.
The Liveblocks client works well with these rooms.
However, the HTTP API breaks when deleting them, even when using the URL Encoding method.
 
Discord: https://discord.com/channels/913109211746009108/913158542565994606/941049335670513664

**Comment by ofoucherot** [comment]
The issue has been fixed!
