### ISSUE TITLE
Throw an error when payloads breach the size limit

### ISSUE THREAD

**Issue by captaindev404** [liveblocks/liveblocks#65]
When a user exceeds the payload size limit (128KiB), the channel subscription does not throw an error.
Generating a specific error would allow the developer to optimize the payload size (splitting large lists of data, ...).

Discord: https://discord.com/channels/913109211746009108/913158542565994606/941052270768971786
Related issue: https://github.com/liveblocks/liveblocks/issues/34#issuecomment-992454696

**Comment by stevenfabre** [comment]
Another person requested this here: https://discord.com/channels/913109211746009108/913158542565994606/1106103402305441852
