### ISSUE TITLE
Improve token types documentation  

### ISSUE THREAD

**Issue by captaindev404** [liveblocks/liveblocks#67]
The "authorize" endpoint can generate tokens usable by the client or the HTTP API.
When no room identifier is sent to the authorized endpoint, the endpoint generates a specific token type.

The client cannot use the generated token.
These attention points might need to be detailed in the documentation.
The error message thrown by the parseToken method may not give enough details, thus making the error challenging to understand.

````
if (typeof data.actor !== "number") {
    throw new AuthenticationError(
      `Authentication error. Liveblocks could not parse the response of your authentication endpoint`
    );
  }
````
 
Discord: https://discord.com/channels/913109211746009108/913158542565994606/941606262796328960

**Comment by GuillaumeSalles** [comment]
Fixed by https://github.com/liveblocks/liveblocks/pull/347
