### ISSUE TITLE
Add SolidJS integration

### ISSUE THREAD

**Issue by nikitavoloboev** [liveblocks/liveblocks#672]
**Is your feature request related to a problem? Please describe.**

Would love to use Liveblocks with [SolidJS](https://www.solidjs.com) but there is no official integration.

There is a JavaScript library and I was told in Discord I can build on top of it.

> javascript package has enough for you to make your own abstractions if needed

> I'd start with some simple handwritten createSignals and createEffects, then pull those into hooks when you want to reuse that

I was also told to open an issue here so that an official integration be added. Ideally with similar template as in this tweet:

https://twitter.com/ctnicholasdev/status/1622977852542160896

**Comment by GuillaumeSalles** [comment]
Hey @nikitavoloboev,

Thank you for your feedback! I added it to our backlog. 

In the short term, the best thing we can provide is these 2 examples:

https://github.com/liveblocks/liveblocks/tree/main/examples/solidjs-live-avatars
https://github.com/liveblocks/liveblocks/tree/main/examples/solidjs-live-cursors

They're built with Solid and are using `@liveblocks/client`

**Comment by nimeshnayaju** [comment]
@GuillaumeSalles  XState recently added a SolidJS integration. Since, both XState and Liveblocks core provide an external store and uses the `useSyncExternalStore` hook for their React implementation, I think this could be a good place to start the investigation.

Link to the PR: https://github.com/statelyai/xstate/pull/2932

**Comment by tmns** [comment]
Whipped together [a pretty rudimentary port of the React hooks](https://github.com/tmns/solid-liveblocks) for a side project. Could maybe hold folks over until something more robust is put together.
