### ISSUE TITLE
[BUG] Client still in presence room even after laptop goes to sleep

### ISSUE THREAD

**Issue by talksik** [liveblocks/liveblocks#679]
**Describe the bug**

I have been trying to figure out why my connections are inconsistent with turning off when a client's computer goes to sleep. Is there some delay in pinging clients to check connection?

I see over and over again where client A saw that client B was connected for hours even when client B computer was in sleep mode.

Device: macbook pro silicon chips | both of them

**To Reproduce**

1. connect client A to a room
2. connect client B to a room
3. Put client b laptop to sleep by closing lid
4. Client B is still shows as connected for client A for hours

**Expected behavior**
I should see that the client B is disconnected and a message sent for presence to the rest of the chat that the client has left.

**Environment (please complete the following information):**
Electron app on both clients. Same app same version.
liveblocks javascript vanilla client sdk

**Comment by talksik** [comment]
can I please get help on this? looking to do a prod release soon :)

**Comment by talksik** [comment]
@taylorpwhipp any ideas here? sorry for bugging you once again

**Comment by nvie** [comment]
Hi @talksik, thanks for filing this report. We'd love to help you out to get this issue addressed.

To confirm and fully understand your bug report, is your problem that there is an inconsistency between two clients' behaviors? For example, if you close the lid of client A and observe with client B: does it work then, but not the other way around?

Or is your bug report that _any_ client that closes their lid never gets cleared from the room?

Do you have a minimal replication (perhaps an online running instance) that we could use to investigate this bug further?

**Comment by talksik** [comment]
Thanks for getting back to me! 

Yep I have tried both ways. both laptops switched.

I also tried the react sdk in addition to js sdk to make sure it wasn't some client side bug. Same issue.

hmmm I don't really have anything other than our beta which you could try theoretically. It's hard to code sandbox this as it's an electron app. Feel free to download and try it with two accounts: https://flowy.live

What I have been seeing clearly is that issue of others firing inaccurate data for others as soon as a client disconnects. Maybe that will help find the bug in your servers. I believe it's what is fired when emitting a disconnect event to other participants on socket disconnect

**Comment by talksik** [comment]
to provide more nuance detail I just noticed. this inaccurate firing of others a split second after the other client disconnects is likely not incorrect state in your servers. If client b refreshes their app, then the `others` event correctly returns empty array []. So:

- client a connects
- client b connects
- both see each other
- client a goes to sleep
- for 200 ms or so, client b gets an event that `others` is empty array []
- right away, client b gets event that `others` is [client a]
- after some time, others fires another event saying []
- after even some more time, maybe 10 minutes, others fires another event saying [client a]

it's really inconsistent, but perhaps that helps in debugging

**Comment by nvie** [comment]
Thanks again for reporting and for providing more details—we'll see if we can replicate this and have someone look into this. If we need more information to debug, we'll get back to you.

**Comment by talksik** [comment]
Thanks! happy to jump on a zoom to show y'all :)

Sorry haha I'm just super impatient when it comes to weird problems that I don't have a proper diagnosis for. Keeps me up hahaha

**Comment by taylorpwhipp** [comment]
> Thanks again for reporting and for providing more details—we'll see if we can replicate this and have someone look into this. If we need more information to debug, we'll get back to you.

Thank you for reaching out, as Vincent had mentioned we are looking into this.

**Comment by talksik** [comment]
yes ma'am, sounds good!

**Comment by ofoucherot** [comment]
Hi @talksik ,
To give you an update, we can reproduce the issue on a Macbook and Chrome browser.

What's happening:
- Client A enters room.
- Client A Macbook goes to sleep
- Chrome closes the Websocket connection.
- After 250ms, Liveblocks client tries to reconnect and can (this is weird). Client A re-enters the room.
- Client A was able to reconnect after the MacBook went asleep, but it doesn't send pings.
- After 2 minutes without receiving any pings, Liveblocks server removes the user.

It corresponds to the scenario that you have:

> - client a connects
> - client b connects
> - both see each other
> - client a goes to sleep
> - for 200 ms or so, client b gets an event that others is empty array []
> - right away, client b gets event that others is [client a]
> - after some time, others fires another event saying []
> 

I'm not sure about this step:
`- after even some more time, maybe 10 minutes, others fires another event saying [client a]`

Is it possible that after 10 minutes, the MacBook woke up for a couple of seconds?


Firefox and other browsers are not having the same behaviours.
In Firefox, the websocket is not being closed properly, the client stops sending pings, and the Liveblocks server "cleans" the inactive user after 2 minutes.

The expected behaviour, which I think you are also expecting, is for the client to disconnect directly when the computer goes to sleep, and be directly removed from the "others" list.
We are trying to find a proper fix for that, just keep in mind that some browsers, in some situations (like going to sleep), don't properly close the Websocket connections. In those cases, there is nothing we can do except remove the users from the server after a period of inactivity. With the current implementation, it's after 2 minutes.

**Comment by talksik** [comment]
@ofoucherot Thank you so much for the detailed answer! 

Appreciate you digging really deep into this. That sounds 100% accurate.

I do think perhaps MacBooks wake up for a couple seconds every now and then. However, it is definitely odd to me that Chrome doesn't close websockets properly. I am going to try a polling workaround through the server side API perhaps. However, I may have to see if this is covered by other alternative products like pusher.

Please let me know when you do find a fix! I assume presence is important to many of your users, and they might just not be catching this bug. Majority of users are likely on Chrome as well.

Once again, thank you for all of the hard work. 🙏🏾

**Comment by ofoucherot** [comment]
To make sure I understand correctly, you have two issues:

1) Users with inactive Websockets connections can be kept in the "others" list for 2 minutes. An inactive Websocket connection is a connection that has not been closed by the client (the browser) but that is not sending pings. This happens almost every time a Macbook goes to sleep.

2) While a Macbook is asleep, the Websocket reconnects (at least for a brief moment).
We weren't able to reproduce this issue yet, we are trying to do it using your Electron app.
Are you able to reproduce it consistently? Is it often after 10 minutes? If yes, would it be possible to send us a screenshot of the messages sent to the Websocket of client B (the other user in the room which is not asleep)? See the screenshot for example:
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/4106249/220415218-b72e9323-c34a-4a3e-a877-02fb6cc08a88.png">


You were also saying that a client was connected for hours while the computer was in sleep mode. Is it still true?

Thank you for your help investigating the issue!

**Comment by talksik** [comment]
Thank you @ofoucherot !

As far as the client was connected for hours while the computer was in sleep mode: I found out that this happens when client A and B are in the room. Client B goes to sleep. Client A goes to sleep. Client B wakes up and still has the same state as before since it never received the event that Client A disconnected. This is why for hours Client B will see client A went to see until perhaps a reload of the app or something.

Is there any way I can short poll presence information? I think it could be a workaround although likely not recommended?

As far as point 2, let me try to emulate that and get back to you! Perhaps I got confused and that wasn't the case 😆 

Once again, appreciate all of the help. Is this a problem every provider would face? Or would you know if another service like Ably would have accounted for this somehow?

**Comment by ofoucherot** [comment]
Thank you for the extra details!

We will try to reproduce this today, if we are able to, it should be easy to fix:
> As far as the client was connected for hours while the computer was in sleep mode: I found out that this happens when client A and B are in the room. Client B goes to sleep. Client A goes to sleep. Client B wakes up and still has the same state as before since it never received the event that Client A disconnected. This is why for hours Client B will see client A went to see until perhaps a reload of the app or something.

> Is there any way I can short poll presence information?

Yes but it's not recommended, the client should always get the proper information from the server.

> As far as point 2, let me try to emulate that and get back to you!

Thank you! We weren't able to reproduce on our side, with your electron app and with another app.


Websockets are shaky and don't always close properly, that's why every WS provider will have a ping/pong mechanism so that the server can clean inactive users after X minutes. We can still improve and optimize our connection retry strategy, but you will have this same issue with other providers.

My goal is to reproduce and fix every issue where the presence of a user is wrong for more than 2 minutes.

**Comment by talksik** [comment]
Got it, that's fair 👍🏾 Ping pong is a good approach to this problem, and a standard one.

I wonder what Slack does to have such an accurate presence status. As well as something like Figma or Notion. They must be doing something to make experiences seamless.

**Comment by ofoucherot** [comment]
Hello @talksik,
We were able to reproduce this and find a fix for this issue:

> As far as the client was connected for hours while the computer was in sleep mode: I found out that this happens when client A and B are in the room. Client B goes to sleep. Client A goes to sleep. Client B wakes up and still has the same state as before since it never received the event that Client A disconnected. This is why for hours Client B will see client A went to see until perhaps a reload of the app or something.

We will publish a new version today or tomorrow. I will let you know when it's done.

For the 2 minutes delay when an inactive client can stay "present", we could reduce it to 1 minute. Do you think it would make a difference?


Thank you again for your help and the details given!

**Comment by talksik** [comment]
That's great to hear! I think one minute is a good step in the right direction! 2x accuracy!


Hope these sorts of things helps liveblocks get to the next level! 🚀

**Comment by adigau** [comment]
_(sorry, just jumping in quickly to say: "Yes it does @talksik! Thank you for raising it! 🙏 It’s really appreciated." )_

**Comment by ofoucherot** [comment]
Hi @talksik,

We released version 1.0.1 with the bug fix!
We also implemented the change to reduce the delay from 2 to 1 minute before clearing inactive users, but we will deploy it in production tomorrow (Feb 25).

Let us know if you have any other issues, and thank you again for using Liveblocks!

**Comment by talksik** [comment]
Awesome @ofoucherot !! Thank you for the so on top of this!

Appreciate it and will keep you in the loop 🙏🏾

**Comment by talksik** [comment]
Circling back here about 

"As far as the client was connected for hours while the computer was in sleep mode: I found out that this happens when client A and B are in the room. Client B goes to sleep. Client A goes to sleep. Client B wakes up and still has the same state as before since it never received the event that Client A disconnected. This is why for hours Client B will see client A went to see until perhaps a reload of the app or something."

What was the fix? I am still seeing the issue. Did the fix include firing a new event on reconnect of client B so that client B can get a fresh list of others?

**Comment by ofoucherot** [comment]
Hi @talksik,

The fix was released on version 1.0.1 of the client [package](https://www.npmjs.com/package/@liveblocks/client/v/1.0.1). Could you confirm that your application is using this version?

**Comment by talksik** [comment]
Ahhh I see sorry about that, I will try that!

I assumed it would be a server side bug, but thank you!

**Comment by ofoucherot** [comment]
Hello @talksik,

Has version 1.0.1 resolved your issue?

**Comment by ofoucherot** [comment]
Hi @talksik,

We were not able to reproduce this issue. I don’t see any path that could result in client B reconnecting if the computer is asleep. 
Are you able to reproduce this issue consistently? 
Do you have any logs sent from your application to verify that the computer did not wake up and reconnect to the internet?

**Comment by talksik** [comment]
@ofoucherot Let me try to reproduce again and show some sort of video to articulate this in the next week or so

Thanks for the help and patience!

**Comment by nvie** [comment]
@talksik Today, we [launched Liveblocks 1.1](https://liveblocks.io/blog/whats-new-in-v1-1), in which we holistically solved all known issues around connectivity. We have never been able to reproduce this exact issue, but given that we holistically rewrote the client's internals, there is a big chance that your issue is also resolved. Would you mind giving it a try? If not, feel free to re-open this issue! 🙏

**Comment by talksik** [comment]
thanks @nvie will give it shot after some re-architecting. we may need some custom presence implementation for rust embedded programming. Will have to look at the raw websocket way of using liveblocks

thank you once again for all of your efforts!

**Comment by nvie** [comment]
Ohh, that'll be a fun project to work on. Lmk if you have any questions! 🙏
