### ISSUE TITLE
[FEATURE_REQUEST] Self-hosting?

### ISSUE THREAD

**Issue by josephrocca** [liveblocks/liveblocks#682]
Hi, just discovered LiveBlocks and I've looked through the readme and some of the site/docs, and I wasn't able to find any info about self-hosting? Apologies if I've missed it, or misunderstood!

**Comment by GuillaumeSalles** [comment]
Hi @josephrocca,

As of today, Liveblock only provides a fully hosted solution. We might provide an on-premise solution in the future, but realistically, it will not happen in the short term.

Closing the issue. Don't hesitate to ask more questions and I'll reopen it if necessary

**Comment by MentalGear** [comment]
Just to be sure, liveblocks, at least the backend, is not open source?

**Comment by nvie** [comment]
We’re planning to open source a server package in the coming months, so stay tuned.

**Comment by MentalGear** [comment]
Hi Vincent, Will this package then allow for complete self hosting? We are cool with paying license fees, but it needs to be under our co trail and run fully on premise.On Feb 16, 2024, at 09:48, Vincent Driessen ***@***.***> wrote:﻿
We’re planning to open source a server package in the coming months, so stay tuned.

**Comment by nvie** [comment]
We’re still figuring some of that stuff out. If you have time, we’d be happy to jump on a quick call to learn more about your use case and share with you how we’re thinking about self-hosting.

**Comment by arkodeep3404** [comment]
is self hosting the cloud available yet?

**Comment by BleedingDev** [comment]
I'd love to have self-hosted version, because we are working with enterprise clients and they really need to have things under their control (not to mention that our app needs to work within intranet).

Anything I can do to help? 😊

**Comment by Jkense** [comment]
> Hi [@josephrocca](https://github.com/josephrocca),
> 
> As of today, Liveblock only provides a fully hosted solution. We might provide an on-premise solution in the future, but realistically, it will not happen in the short term.
> 
> Closing the issue. Don't hesitate to ask more questions and I'll reopen it if necessary

Is this still on the roadmap? If not, can we choose database location?

**Comment by ryanhugh** [comment]
We are also interested and also happy to pay license fees, but are only interested if we can self-host it. Please let me know when you have added support for this feature.

**Comment by jan10** [comment]
@GuillaumeSalles any updates on this?

**Comment by codebyvineet** [comment]
We are also interested and ready to pay license fees, but as other mentioned  interested if we can self-host it.

**Comment by mhbdev** [comment]
Any updates?
