### ISSUE TITLE
Angular framework support

### ISSUE THREAD

**Issue by horationunez** [liveblocks/liveblocks#708]
Howdy, I was wondering if there are plans to ship a helper package for the Angular framework.

Thanks in advance for any insight.

**Comment by nvie** [comment]
Hi @horationunez, we don't have any plans for that, but you should be able to use it in Angular by using the plain JavaScript client from `@liveblocks/client` and entering/leaving a room programmatically yourself.

Relevant documentation:
- Getting started guide for JavaScript: https://liveblocks.io/docs/get-started/javascript
- API reference for `@liveblocks/client`: https://liveblocks.io/docs/api-reference/liveblocks-client

Please let us know if you run any any issues with that, we're happy to help in case you feel stuck.
