### ISSUE TITLE
[BUG] LiveList insert and set the same block events quickly

### ISSUE THREAD

**Issue by weiningning** [liveblocks/liveblocks#731]
I encountered a problem when developing collaborative editors with Liveblocks and slatejs in our Web App[[Allset](https://www.allset.day/)]

## Describe the bug

Locally, LiveList inserts blockA + sets blockA quickly, and the local subscribe will receive two updates.

These two updates have passed, and the business layer will use these two ops, leading to bugs.

https://user-images.githubusercontent.com/20291747/223987967-e4b75e1a-b9cf-4ab7-9ce9-364a0ade86c6.mov

The  editor example of Liveblocks also has the same problem：

https://user-images.githubusercontent.com/20291747/223988106-0dd9ac26-cc54-476e-b0ef-63f417401094.mov

## Expected behavior

Locally does not accept any updates changed by itself.

[Currently, when inserting blockA and setting blockA, there is an interval between them, and the local will not receive any updates, which meets the requirements.]

## P**roblem a**nalysis

Looking at the Liveblocks source code, my analysis is:

### Operating block

1. Insert blockA "op.id:4248:0":
    - Add block "op.id:4248:0" to this._pool.
2. Set blockA "op.id:4248:1":
    - Detach blockA "op.id:4248:0" from this._pool.
    - Attach "op.id:4248:1" to this._pool.

At this time, this._pool only records the current "op.id:4248:1" block.

### onMessage  callback

Then, onMessage listens to messages from ws:

Receive two updates at a time, one is the previous insert blockA "op.id:4248:0" and the other is set blockA "op.id:4248:1".

applyOp:

- Op is insert blockA "op.id:4248:0":
    - When _applyInsertAck:
    Because this.__pool deleted blockA "op.id:4248:0" when blockA was assigned "op.id:4248:1"), this__pool now lacks blockA "op.id:4248:0", so a blockA "op.id:4248:0" is created and an update is generated. The logic goes to the red box below.
![Untitled](https://user-images.githubusercontent.com/20291747/223988627-2f2676a9-b72b-4a84-bfeb-2c2a9e765da6.png)

*I think this op is not found in  this._pool, and there is already a block at the same position, so this op can be considered as a past action, and it can be discarded directly. I don't know if this will cause other problems.*

- Op is set blockA "op.id:4248:1":
    - When _applySetAck,
    Set blockA "op.id:4248:1": this._pool has blockA "op.id:4248:1", then confirm, no new updates are generated, but deleteId is "op.id:4248:0", at this time this__pool has blockA "op.id:4248:0", so a delete update is generated. The logic goes to the red box below.
![Untitled](https://user-images.githubusercontent.com/20291747/223988873-04bf2f30-bccb-4c8f-9fb3-1924dce52110.png)

*If the above insert op is directly discarded, then there is no need to generate a delete update here。And the business layer will not receive any updates.*

### room.subscribe callback

In the callback of room.subscribe , i  receive the following two updates
![image](https://user-images.githubusercontent.com/20291747/223988999-0c1f01e7-f294-49ee-99bd-78c477302896.png)

## Environment

"@liveblocks/client": "^1.0.0",
"@liveblocks/react": "^1.0.0",

**Comment by stevenfabre** [comment]
Thank you for the detailed bug report. There is definitely something off here.

We will get this one prioritized and report back here when it's fixed.
