### ISSUE TITLE
Offline support with persistent storage

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#747]
If a user is temporarily disconnected from the internet, Liveblocks keeps the storage modifications in memory and solves the conflicts when the user gets back online. The modifications are lost if the user closes their tab while offline. We want to solve this by persisting the storage and temporary changes. We want to provide the hooks to persist it to IndexedDB and potentially other local storage solutions for non web environments.

### Part 1 - Focusing on not losing any data

Allow the developer to pass an `OfflineStorage` implementation when creating the client. 
`OfflineStorage` should implement functions to persist/delete unacknowledged modifications.

**_The exact function signatures should be defined after taking performance into consideration. IndexedDB writes can be slow if not done properly._**

The room will use the `OfflineStorage` implementation and persist the unacknowledge operations at an arbitrary frequency.

When the user goes back online, the room will get the latest version of the storage from the server and apply the persisted operations on top of it. As we already do with in-memory modifications. Then we clear the pending modifications from the `OfflineStorage`.

Race conditions are to be taken into consideration. If a user closes the app after some operations are persisted in the `OfflineStorage` and before the server has time to acknowledge these operations, stale changes could be cached and could lead to subtle issues.

If `OfflineStorage` is not provided, we use the incoming storage coming from the server.

**⚠️  Security concern ⚠️ The developer will have to delete any data persisted in the offline storage after a user sign out of the app.**

### Part 2 - Full offline support

The user should be able to see the persisted room storage even after reopening the app while offline. To achieve this `OfflineStorage` should implement additional functions to persist the room storage. Once again, performance is a concern for large documents. 

The client should also be able to detect that the user is offline to load the offline storage without connection to any WebSocket or calling any authentication endpoints.

This assumes that the parts of the app that are not related to Liveblocks also support a full offline experience.

### Part 3 - Providing hooks for the developer to show merge conflicts

With parts 1 and 2, large diffs and conflicts are more likely to happen. Our optimistic approach to solving conflicts will not always work. Effectively representing diffs visually is a domain-specific problem. Solving it in a general way is impossible, so the best thing we can do is provide hooks to let the developer show a diff/merge UI when necessary.

### Related ressources

https://www.figma.com/blog/behind-the-feature-autosave/

**Comment by benkingcode** [comment]
Is this still coming? I was a bit bummed to see the data unavailable when refreshing with my WiFi turned off.
