### ISSUE TITLE
RFC: Supporting an `unknown` type in schemas

### ISSUE THREAD

**Issue by nvie** [liveblocks/liveblocks#796]
This proposal suggests the addition of adding an `unknown` type as a built-in to the schema language, to effectively disable runtime validation for specific subtrees, while still allowing schema validation for other parts of the storage tree.

```graphql
type Storage {
  name: string
  data: unknown  # Can take any value
}
```

# Motivation
In some cases, it may be necessary to skip the validation of a specific field or subtree of a schema during runtime. For instance, when an app allows for external inputs or otherwise (deliberately) unknown data shapes.

# Proposal
We propose the introduction of a new built-in type called `unknown`, which would match every possible runtime value, and never reject a value.

## Behavior in unions
Since `unknown` values could be anything, they cannot appear in a union. Put differently, a union member that is `unknown` is incompatible with all other union members.

```graphql
type Storage {
  data: unknown | string
  #               ^^^^^^ Type 'string' cannot appear in a union with 'unknown'
}
```

## Limit it to only JSON?
An interesting edge case appears when thinking about where to allow the `unknown` type.

Consider these two cases:

```graphql
type Storage {
  foo: Foo
}

type Foo {
  data: unknown
}
```

Here, `Foo` is used as a JSON object (because it isnt referenced as `LiveObject<Foo>`), and thus, `data` will only ever contain legal JSON values.

However:

```graphql
type Storage {
  foo: LiveObject<Foo>
}

type Foo {
  data: unknown
}
```

Here, `Foo` is a LiveObject, so data can potentially be any **LSON** value. Do we want to allow data to be a `new LiveList()`, for example? To me, `unknown` would imply yes.

Or do we want to limit it to just JSON values? And if so, should we also offer a `Json` type for that? They would be almost equal, except that it would not allow any “live values” at runtime.

## Why `unknown`, and not `any`?

In TypeScript, `any` _disables type checking_ completely for a value, while `unknown` is a perfectly valid type that is truly unknown. TypeScript will force you to refine `unknown` (for example, using `typeof` checks), so you can safely access what's inside.

```ts
const x: any = someAny();
const y: unknown = someUnknown();

x.foo.bar[0].qux  // ✅ allowed, but bad practice 🤔 
y.foo             // ❌ disallowed, 'y' is of type 'unknown' 👍
```

To help people out, we could add a parser hint like `Did you mean 'unknown'?` whenever it encounters an `any` type. This might make adoption easier.

# Drawbacks
The addition of the `unknown` type could potentially reduce the effectiveness of runtime validation if people use it when they don’t know how to type their data otherwise. In TypeScript, this often happens with the `any` type. Such practice is ideally not recommended, but using `unknown` deliberately—when the data shape is actually unknown—can be useful.

# Credits
Thanks go out to @FlowFlorent for first surfacing this idea in a meeting.

**Comment by GuillaumeSalles** [comment]
Nice! I like it! 

I agree with `unknown` = `LSON` and we potentially provide a `JSON` validator later.

Why `unknown` and not `any`?

**Comment by nvie** [comment]
> Why `unknown` and not `any`? I'm sure you have your reason but I would love to see the reasoning clearly stated.

Added a new section to explain **"Why `unknown`, and not `any`?"**.
