### ISSUE TITLE
[FEATURE_REQUEST] Make .test domains behave like localhost for MAU purposes

### ISSUE THREAD

**Issue by nik-418** [liveblocks/liveblocks#806]
**Is your feature request related to a problem? Please describe.**

Currently, if I'm developing locally and using a host like `http://myapp.test`, it will count against my MAU, whereas `localhost` won't. `.test` domains are local-only.

**Describe the solution you'd like**

Treat `.test` the same as `localhost` for MAU-counting purposes.

**Additional context**

🤙

**Comment by nvie** [comment]
Ah yes, great idea — we'll get this fixed. I'll let you know when it's fixed 👍

**Comment by nvie** [comment]
This should be fixed now. Thanks for reaching out and informing us about this oversight on our end 🙏 ! Hopefully this is a better experience for you. Please let us know if anything about this isn't working as expected.
