### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by nandorojo** [liveblocks/liveblocks#82]
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/13172299/157786871-4f8df495-6c78-4e8a-98fe-8911d230e354.png">

This says to use your "secret key". Shouldn't it be the public one?

**Comment by GuillaumeSalles** [comment]
@nandorojo Oops! Thanks for flagging it! 

I just deployed a fix

**Comment by nandorojo** [comment]
cool! can i use this with RN btw? i assume not the selection or cursor, but maybe headless presence? (just getting familiar with live blocks)
