### ISSUE TITLE
[BUG] Flowchart example's documentation is wrong

### ISSUE THREAD

**Issue by ysds** [liveblocks/liveblocks#825]
**Describe the bug**

Setup according to this document https://liveblocks.io/examples/collaborative-flowchart/zustand :
```
npx create-liveblocks-app@latest --example nextjs-flowchart --api-key
```

will result in the following error:
```
✖ Repo does not exist: liveblocks/liveblocks/examples/nextjs-flowchart
```

**To Reproduce**

1. See above

**Additional context**

I think this is a documantation bug. `nextjs-flowchart` should be `zustand-flowchart`

**Comment by CTNicholas** [comment]
Hey @ysds, thanks for highlighting this! You're right, it should be `zustand-flowchart`—I've fixed the command now, and it'll update soon:

```bash
npx create-liveblocks-app@latest --example zustand-flowchart --api-key
```
