### ISSUE TITLE
[BUG] Unable to Use Tailwind CSS in Liveblocks Starter Template

### ISSUE THREAD

**Issue by CodeWizarz** [liveblocks/liveblocks#829]
Description:
I tried to use Tailwind CSS in Liveblocks' Starter Template, but I encountered an issue. When I added the Tailwind classes to the HTML elements in the template, they didn't get applied to the page. I checked the console for any errors and found none. I also verified that the Tailwind CSS file was loaded correctly in the template.

Steps to Reproduce:

Create a new project on Liveblocks using the Starter Template.
Install Tailwind CSS using npm or yarn.
Add the Tailwind classes to the HTML elements in the template.
Preview the page in the browser.
Expected Results:
The Tailwind classes should be applied to the HTML elements, and the page should display with the correct styles.

Actual Results:
The Tailwind classes are not applied to the HTML elements, and the page displays with the default styles.

Environment:

Operating System: [Linux(ubuntu 22)]
Browser: [Chrome, Firefox, Edge]
Tailwind CSS
Workaround:
There is currently no known workaround for this issue.

Additional Information:
I have tried adding the Tailwind classes to a blank HTML file outside of the Liveblocks environment, and they work correctly. This issue only occurs when using the Liveblocks Starter Template.

**Comment by CTNicholas** [comment]
Hey @CodeWizarz! I've identified the source of the issue, it's being caused by an existing `postcss.config.js` file that has no Tailwind config inside it.

Here's how to fix it in the starter kit:
1. Delete `postcss.config.js` in the starter kit
2. Run `npx tailwindcss init -p`

If this doesn't work, delete the `.next` directory and try it again. 

Could you let me know if that works for you?

**Comment by CodeWizarz** [comment]
No i guess i tried all the possible solutions and the above you provided 
## although ill provide my configs 
### postcss.config     module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
} 
### tailwind.config      /** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}", "./components/**/*.{html,js,ts,jsx,tsx}", "./pages/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
}

**Comment by CodeWizarz** [comment]
Yeah It works just fine thank you. I'm gonna see what's wrong with my config files.

**Comment by CTNicholas** [comment]
> ##### Yeah It works just fine thank you. I'm gonna see what's wrong with my config files. And by the way i tried to replicate the on hover dropdown component in liveblocks official webpage using tailwind and pure css too, it feels more complicated than it looks. Is it possible you can help me any way ? thanks in advance :)

Great, glad it works @CodeWizarz! 

Have you seen this? 😄 
https://twitter.com/brentarcane/status/1651007781481357312

Someone recently replicated the header and made it open-source!

**Comment by CodeWizarz** [comment]
@CTNicholas thanks Nick i was desperate to replicate the header. :)
