### ISSUE TITLE
[BUG] Collaborative Flowchart example has no nodes

### ISSUE THREAD

**Issue by johnrobbjr** [liveblocks/liveblocks#856]
**Describe the bug**
The Collaborative Flowchart example shows a React Flow component with no visible nodes, and there is no way to add a new node in the interface. https://liveblocks.io/examples/collaborative-flowchart/zustand

**To Reproduce**

1. Open https://liveblocks.io/examples/collaborative-flowchart/zustand
2. Try using the example at the top of the page

**Expected behavior**

I should see the same nodes in both React Flow components on the example at the top of the page

**Illustrations**
<img width="1440" alt="Screen Shot 2023-05-02 at 15 49 00" src="https://user-images.githubusercontent.com/9868315/235686280-aae9620d-798a-462b-a4ac-f37c8808bacc.png">

**Environment (please complete the following information):**

- Tested on Brave Browser Version 1.50.121, Chromium: 112.0.5615.138 (Official Build) (arm64), and Safari Version 15.5 (17613.2.7.1.8)

**Additional context**

React Flow prevents the problem of having an empty live collaborative example by including a sidebar to drag-and-drop new nodes from, so if someone deletes all of the nodes, new ones can be added.
- Collaborative example: https://reactflow.dev/docs/examples/interaction/collaborative/
- Drag-and-drop interface example: https://reactflow.dev/docs/examples/interaction/drag-and-drop/

Thanks! 🌻

**Comment by CTNicholas** [comment]
Thanks for the heads up, I'll take a look into this 👍

**Comment by CTNicholas** [comment]
We normally have examples entering a fresh room each time the page is loaded, but we had a small error in the code preventing this. Now the flowchart should display correctly every time 🙂 https://github.com/liveblocks/liveblocks/pull/860
