### ISSUE TITLE
Remove private field usage to simplify bundling

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#87]
We're currently using [private fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#private_fields) and [private methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#private_methods). 

While this is better for encapsulation, they are not widely supported (less than 90% based on Caniuse). Babel injects a lot of code on hot paths which arguably outweighs the benefit of encapsulation. Removing private fields and methods in favor of `@internal` to hide them from auto-completion would improve our final bundle.

**Comment by nvie** [comment]
This was addressed in #106.
