### ISSUE TITLE
Improved status subscription APIs

### ISSUE THREAD

**Issue by CTNicholas** [liveblocks/liveblocks#878]
Currently if you use `room.subscribe("connection")` a number of different statuses can return: `authenticating`, `connecting`, `open`, `failed`, `closed` or `unavailable`. These are the statuses the users sees when connecting to Liveblocks: `closed -> authenticating -> connecting -> open` . 

However, when building your UI/app, most of these statuses are _not helpful_, as they're too low-level. @nvie and I came up with the idea of two new subscriptions, which we're calling `room.subscribe("status")` and `room.subscribe("lost-connection")`, which can hugely simplify things for the user by providing a higher-level abstraction.

## `room.subscribe("status")` 

This would **replace** `room.subscribe("connection")` and would return much more user friendly connection statuses. 

```ts
type Status =
  | "initial"
  | "connecting"
  | "connected"
  | "reconnecting"
  | "disconnected"

room.subscribe("status", (status: Status) => {
  // "initial" | "connecting" | "connected" | "reconnecting" | "disconnected"
  console.log(status)
})
```

- The state when loading the page would be `initial -> connecting -> connected`.
- If you lose connection, you will see `reconnecting -> connected`.
- If you fail to authenticate, you will see `disconnected`.

## `room.getStatus()`

This will replace the current `room.getConnectionState()` API.

```ts
// ❌ Old synchronous API
room.getConnectionState()  // "closed" | "open" | "authenticating" | "connecting" | "unavailable" | "failed"

// ✅ New/proposed synchronous API
room.getStatus()  // "initial" | "connecting" | "connected" | "reconnecting" | "disconnected"
```

Note that the new API will no longer let you programmatically distinguish the "authenticating" from "connecting" state, but I don't think it matters at all to an end user? Getting a notification of a change from `authenticating` → `connecting` isn't really actionable for any app.

### React hook: `useStatus`

We could then turn this into a React hook which would be used for displaying the current connection status, for example in a badge.
```tsx
const emoji = { initial: "⚪", connecting: "🟡", connected: "🟢", /* ... */ };

function Component() {
  const status: Status = useStatus();

  return <div>{emoji[status]}</div>;
}
```

## `room.subscribe("lost-connection")`

A new "convenience" subscription which would be used primarily for toast notifications. The callback will only be called if a connection is ever lost. This subscription will not ever be called on an initial successful connection.

```ts
type LostConnectionEvent =
  | "lost"      // the client is reconnecting to Liveblocks, but it's taking much longer than usual
  | "restored"  // the client did reconnect after all
  | "failed"      // the client was told to stop trying

room.subscribe("lost-connection", (event) => {
  // "lost" | "restored" | "failed"
  console.log(status);
})
```

- Never called unless a problem occurs (and only after first having been connected successfully)
- `lost` is sent only after a short delay if normal reconnection is taking way longer than usual (e.g. ~5s) to allow for minor connection hiccups to be ignored
- If you lose connection, you will see `lost` → `restored`
- If you fail to authenticate, you will see `failed`, indicating that the reconnection attempt has been given up

To be clear about the relationship with the new synchronous `.getStatus()` API:
- If called with `event === "lost"` then `room.getStatus()` will be `"reconnecting"` (and it will have been "reconnecting" for the last 1.5 seconds)
- If called with `event === "restored"` then `room.getStatus()` will be `"connected"`
- If called with `event === "failed"` then `room.getStatus()` will be `"disconnected"` too

### React hook: `useLostConnectionListener`

This subscription is ideal for creating a React listener that can be used with a toast notification library, for example with the popular [react-toastify](https://www.npmjs.com/package/react-toastify) package.

```tsx
import { toast } from "react-toastify";

function Component() {
  const toastId = useRef(null);
  
  useLostConnectionListener((event: LostConnectionEvent) => {
    if (event === "lost") {
       // Yellow toast
       toastId.current = toast("App currently reconnecting...");
    } else if (event === "restored") {
      toast.dismiss(toastId.current);
    } else if (event === "failed") {
       // Red toast
       toastId.current = toast("App could not reconnect. Please try reloading the page.");
    }
  });
}
```

<details>

<summary>How to do this with our current APIs</summary>

```ts
import { toast } from "react-toastify";

function Component() {
  const room = useRoom();
  const toastId = useRef(null);
  const hasEverConnected = useRef(false);
  const timerId = useRef();
  
  useEffect(() => {    
    const unsubscribe = room.subscribe("connection", (status) => {
      if (status === "open") {
        hasEverConnected.current = true;
      }
    
      if (!hasEverConnected.current) {
        return;
      }
    
      if (status === "open" || status === "closed") {
        clearTimeout(timerId.current);
        toast.dismiss(toastId.current);
      } else if (status === "failed") {
        toastId.current = toast("Liveblocks connection could not be established")
      } else {
        timerId.current = setTimeout(() => {
          toastId.current = toast("App currently reconnecting...");
        },
        // Give Liveblocks 1.5 seconds before showing
        // the "reconnecting" toast message
        1500);
      }
    });
    
    return () => unsubscribe();
  }, [room]);
}
```

</details>

### Comparison

Implementing a toast notification with `@liveblocks/client`:

<details>

<summary>With `room.subscribe("connection")`</summary>

```ts
let hasEverConnected = false;
let timerId;

room.subscribe("connection", (status) => {
  if (status === "open") {
    hasEverConnected = true;
  }

  if (!hasEverConnected) {
    return;
  }

  if (status === "open" || status === "closed") {
    clearTimeout(timerId);
    toast.clear();
  } else if (status === "failed") {
    toast.error("Liveblocks connection could not be established")
  } else {
    timerId = setTimeout(
      () => {
        toast.info("Liveblocks is reconnecting...");
      },
      // Give Liveblocks 1.5 seconds before showing
      // the "reconnecting" toast message
      1500
    );
  }
});
```

</details>

<details>

<summary>With `room.subscribe("reconnection-issue")`</summary>

```ts
room.subscribe("lost-connection", (event) => {
  if (event === "lost") {
    toast.clear();
  } else if (event === "restored") {
    // Would only be emitted after 1.5s, otherwise users would not even see
    // this happening
    toast.info("Liveblocks is reconnecting...");
  } else /* event === 'failed' */ {
    toast.error("Liveblocks disconnected permanently");
  }
})
```

</details>

Please let us know your thoughts!

**Comment by nvie** [comment]
Fixed and implemented in #934 + #935. Will land in 1.1.0 beta.
