### ISSUE TITLE
Requests from Cloudflare Workers on the Edge to MongoDB are blocked from Russian IP's

### ISSUE THREAD

**Issue by taylorpwhipp** [liveblocks/liveblocks#888]
Context: 

After some investigation, we have determined that Cloudflare workers (which live on the edge and are used in our backend) are reaching out to our database from an IP in Russia (when the origination is in parts of Europe close to Russia), which is automatically blocked. This is a challenging fix.   

We are creating this GitHub issue to track the resolution of the problem from our end/ provide updates, and note any changes that our providers put in place that would fix the is sue or make it more complex. 

[Mongo DB Reference](https://www.mongodb.com/blog/post/mongodb-assistance-ukraine-shut-down-work-russia)

**Comment by nvie** [comment]
This has been resolved.
